M7R0
I'LieAlg=6"%&falseGE\[lK%#&*Gt+6$'%"AG%)anythingG'%"BGF,6'%$AlgG%+CheckConstG%)
GetTermsG%*GetConstsG%(IsConstG6#%fnCopyright~(c)~2001-2004~by~Yuly~Billig~and~
Matthias~Mazzag.G6"C'>8(t+6%'%"EGF,'F1%(booleanG'F0%%nameGF7F7F7-%'RETURNG6#-%&
evalbG6#5-%#isG6$9$%)constantG33-FK6$FMFB9%4-%,isgeneratorG6$FM9&F7F7F76#""$>8&
t+F<6#%"iGF7F7-FD6#-%'subsopG6$&-%$mapG6&f*6%%"xG%"yG%"zGF76$%)operatorG%&arrow
GF7@$-T#6%&FM6#""#FSFXO/&FM6#"""FfpF7F76$F4F]p7#-%$seqG6$7$8$-%#opG6$F]qFM/F]q;
Ffp-%%nopsG6#FMFSFXF7FMF7F76$F4F:6#FZ>8't+F<FhnF7F7-FD6#-F]o6$&-Fao6&f*FdoF7Fho
F7@$4F\pOFcpF7F7FgpFhpFSFXF7FMF7F7Ffq6#FZ@%2Fap9#C$>F]q&9"6#FZ>8%%%trueG>F`sF%@
-5-F:6%FMF`sF]q-F:6%FSF`sF]q-FD6#*&FMFfpFSFfp355-%%typeG6$FM%(indexedG-F`tFR-F`
t6$FM%)functionG55-F`t6$FSFbt-F`t6$FSFft-F`t6$FSFB@'-F`t6$FM%#&^G-FD6#-%&evalnG
6#-%#&@G6$-Fbu6$-F_q6$FfpFM,&-F_q6$FapFMFfp!""Ffp-F'6$F]vFS3-F`t6$FMF'-F`t6$FSF
bu-FD6#-Ffu6#-Fiu6$-F'6$FM-F_q6$FfpFS-Fbu6$Fbw,&-F_q6$FapFSFfpFbvFfp-FD6#-Ffu6#
-F'6$FMFS-F`t6$FM%"*G@%4-F`t6$7#-F_qFeq-%%listG6#FB@%F`s-FD6#*&-FiqFfsFfp-F'6%-
FfnFfsFSF]qFfp-FD6#*&F_yFfp-F'6$FbyFSFfpFiw-F`t6$FSFax@%4-F`t6$7#-F_q6#FSFhx@%F
`s-FD6#*&-FiqFhsFfp-F'6%FM-FfnFhsF]qFfp-FD6#*&FezFfp-F'6$FMFhzFfpFiw5-F`t6$FM%"
+G-F`t6$FSFa[l@%F`s-FD6#-%.generalexpandG6&FMFSF'F]q-FD6#-Fh[l6%FMFSF'-%&ERRORG
6%%H%1,~%2~are~not~defined~in~this~context.GFMFS6#%epOverloaded~operator~that~r
epresents~non-communitative~multiplication~used~in~lie~algebras.GF7F76#Fap%/sin
gularvectorGt+6$'%'WeightG-Fix6#%(integerG'%%ListG-Fix6#%*algebraicG6(F0F.%"MG%
$HWVG%%NofRGFin6%%)rememberG%'systemGF6F7C)@'2FZFir-F_\l6$%7too~many~arguments~
%1.GF]s/FirFZ@%-F`t6$F\s%&hwrepG>F:F\s-F_\l6$%W%1~is~not~a~representation~or~qu
otient~representation.GF\s>F:%/REPRESENTATIONG>F]q&&-F_q6$""%-%%evalG6#Fc^l6$F:
%(algebraGF`p>Fiq&F]_l6#F:@$-%'memberG6$7"-Fao6%f*6$%"eG%"aGF7FhoF7-%#wtGF^xF7F
7F7FSF]q-F_\l6%%Nelements~%1~of~algebra~%2~are~not~homogenous.GFSF]q>F`s-%&basi
sG6$FMF:>Ffn-%(convertG6$-%$<,>G6#-F_q6#-Fao6)f*6(Feo%#blG%"wG%"rGFb`l%$hwvGF7F
hoF7-%$<|gr>G6$%"%G-F_q6#-Fao6)t+6(%"uGFeo%#vlGF[blFb`lF\bl6$%"sG%"kGF7F7C$>F]q
-%,repsimplifyG6$-Fiu6$FSFM9'@+-F`t6$F]qFa[l-FD6#-Faal6#-F_q6#-Fao6&t+6%%"tGFhb
l%$vllG6#F[clF7F7@'3F_x-Fj_l6%-%)PickTermGFeqFS.F]q-FD6#7%-Fjp6$""!/F]p;Ffp,&F]
qFfpFbvFfp-%.PickConstantsGFeq-Fjp6$F`el/F]p;,&F]qFfpFfpFfpFX-Fj_l6%FMFSFjdl-FD
6#7%F^elFfpFfel-F_\l6%%7%1~is~not~in~basis~%2.GFMFSF7F76$FinF]p6#FZF]qFX-Fdq6#F
X3-F`t6$F]qFax-Fj_l6%-Fidl6#F]qFX.F`s-FD6#-Faal6%-Fjp6$F`el/F]p;Ffp,&F`sFfpFbvF
fp-FeelF]gl-Fjp6$F`el/F]p;,&F`sFfpFfpFfpFefl-Fj_l6%F]qFXF^gl-FD6#-Faal6%FcglFfp
Figl/F]qF`el-FD6#-Faal6#-Fjp6$F`el/F]pFX-F_\l6%FbflF]qFXF7F7Fcfl6#""'FSFM-Fj`l6
$,&-Fd`l6$FM9(FfpFXFfpFcclFcclFeil9)F7F76$Fin8)FSF`sFMF:F]qFiq%'matrixG@%/%/CHA
RACTERISTICGF`el-FD6#7#&-Fao6%f*6$%"vG%"bGF7FhoF7-%$addG6$*&&FM6#F]pFfp&FSF\[mF
fp/F]p;Ffp-Fdq6#-F^al6$FMFixF7F7Fgil-&%'linalgG6#%*nullspaceG6#FfnF`sF7-FD6#7#&
-Fao6%f*FdjlF7FhoF7FgjlF7F7Fgil-%$modG6$-%*NullspaceGFi[mF\jlF`sF76#%XCalculate
s~the~singular~vectors~for~the~representation.GF7F76#Fap%&storeGt+F76,%$rhsG%$l
hsG%$resGFin%"jG%&TableG%$NORG%$EndGF0%+createfuncGF5F7C'>8-t+6%F]]mF\]mF^]mF7F
5F7@%53F_t-%(hastypeG6$FfxFB3Fit-F]^m6$F^zFB-FD6#-%(unapplyG6$FX&7$&FfxF7&-Fao6
%f*6$Fin%"lGF7FhoF7@$4-Fj_lF^xFMF7F7F7F^zFfxF7F7-FD6#-Fe^mFffl6#%GCreates~a~fun
ction~from~an~expression.GF7F76#FZ@'/FirF`el-FDF7/&F]s6#Fir%'silentG>8*,&FirFfp
FbvFfp>Fa`mFir-%*resettabsG6#7'%,functionizeG%.mainlsimplifyG%.mainasimplifyG%0
mainrepsimplifyG%'reduceG?(FiqFfpFfpFa`mFasC$@)4-F`t6$&F]s6#FiqFix-F_\l6$%Gexpe
cted~a~list~of~rules,~received~%1.GFcam32F`el-Fdq6#Fcam-F`t6$&F]s6$FiqFjamFBC$>
8+,&FjamFfpFbvFfp>8,F^bm/%+GENERATORSGF\`l-F_\l6#%iocan't~set~rules~for~default
~algera,~since~there~is~no~default~algebra~defined.GC$>FbbmFjam>Febm%(ALGEBRAG@
%/&F]s6$Fiq;FfpFbbmF\`l@$0-F_q6$F__l-Fa_l6#%*withrulesG%%NULLGC%>Fhil&-F_q6#Ffc
mFep-Fe`m6#7#Fjcm-Fao6$f*6#FeoF7FhoF7@$0F]vF]p>-Fjcm6#F]vF`vF7F76$F0FebmFhilC$?
(F:FfpFfpFbbmFas@%4-F`t6$&F]s6$FiqF:%"=G-F_\l6$%Eexpected~an~expression,~receiv
ed~%1.GFdemC)@$550-Fdq6#&FcamFg_lFap0-Fdq6#-F_q6$FfpFafmFap-F`t6$FefmFbt-F_\l6$
%hnincorrect~rule~%1,~the~correct~form~is:~[name]&*[name]=[expr]GFcam>F`s-F_q6$
FfpFefm>F]q-F_q6$FapFefm>Ffn-F_q6$FapFafm@$5-FK6$F`sFN-FK6$F]qFN-F_\l6$%jnincor
rect~rule~%1,~no~constants~are~allowed~in~the~LHS~of~expr.GFafm@$/-Fh`m6$-Ffu6#
-F'6$F`sF]qFebm%%FAILGC%>FhilFfcm@$5/FhilF[dm30FhilF[dm4-Fj_l6$7#Febm7#-%(indic
esG6#Fhil>-Fjcm6#FebmF\`l@%0F`sF]q>Fgim7%&FgimF7/Fdhm-Ff]m6%F`sF]qFfn/-F'6$F]qF
`s-Ff]m6%F]qF`s,$FfnFbv>Fgim7$F]jmF^jm@$0F]`mF_`m-%&printG6#/FbhmFfn-Fe`m6#7#Fh
`m-FD6#F[dm6#%instore()~saves~a~given~rule~and~its~reverse~in~the~lookup~tableG
F7F76#F`el%#&>Gt+6$'F+Fa]l'F.Fa]l6%%#LAG%#LBGFinF5F7C'@%F_[l>F]q-%(leadingG6$FM
F^cm>F]qFM@$Fhfl>F]qF\gl@%Fb[l>F`s-Fc\n6$FSF^cm>F`sFS@$-F`t6$F`sFax>F`s-Fidl6#F
`s@%-F]^m6$FgbmFbt-FD6#-FG6#2F`el-%'tcoeffG6#,&-%/indexedrankingG6$F]qF^cmFfp-F
`^n6$F`sF^cmFbv-FD6#-FG6#2-%.normalrankingGFc^n-Fj^nFa^n6#%gtmonomial~&>~monomi
al~defines~the~operator~"&>",~which~is~interface~to~the~|+~~~~~~~~~~~~~~~~~func
tion~evaluate;~works~only~with~the~default~set~of~generatorsGF7F76#Fap%'affineG
t+6$'%&LabelGFB'%'CartanGFB6)FinF_]mF[bl%%GensG%"nG%$WtsG%%TempGF5F7C,Fg]l@%2F_
_lFirF\^lC&>Fiq7%.Fa`l.%"hG.%"KG>FhilF\`l>Fa`mF\`l?(F]qFZFfpFirFasC$>Fa`m7$&Fa`
mF7&F]sF]gl@'3-F`t6$F]anFhx/-Fdq6#F]anFZC$>FiqF]an>&Fa`m6#-Fdq6#Fa`m&Fhan6#;Ffp
Fap-F`t6$F]an-Fix6#Fix>FhilF]an-F_\l6$%foinvalid~parameter~%1~(expected~a~list~
of~generators~and~a~list~of~weights).GF\s@%554Fit0-FdqF`zFfp4-F`t6$F_zF\]l-F_\l
6$%S%1~is~an~incorrect~name~for~type~of~Cartan~matrix.GFS>F:F_z>F[cl.F[cl>Fiq7%
&&FiqFep6$-Fjp6$(FfnF`s/F`s;FfpF:F[cl&&FiqF`p6$(F]qFfpF[cl&FiqF^s@$/FhilF\`l>Fh
il7%7$F[dnF[cl7$-Fjp6$F`elF^dnF[cl7#-Fjp6$F`el/F`s;Ffp,&F:FfpFfpFfp@$/Fa`mF\`l>
Fa`m7#Fhil>Fa`m-%%subsG6%/F[clF`el-Fjp6$/(FfnF]q(F[clF]q/F]qF_dnFa`m>-F__nFeq-F
_q6$Ffp&7#-%'simpleG6%-%$catG6$FM%(_simpleGFSF\anFep-FD6#-%+generatorsG6%FMFiqF
hil6#%Ssupports~the~declaration~of~affine~simple~algebrasG6&Fa`lFc`nFe`nF[clF76
#Fap%$&<=Gt+Fi[nF7F5F7-FD6#4-Fg[nF^x6#%htmonomial~&<~monomial~defines~the~opera
tor~"&<=",~which~is~interface~to~the~|+~~~~~~~~~~~~~~~~~function~evaluate;~work
s~only~with~the~default~set~of~generatorsGF7F76#Fap%(quotrepGt+6$Fb_n'%'SubModG
%*submoduleG6#%&HWRepGF5F7C-Fg]l@$F[^lF\^l>F]q&-F_q6$F__l-Fa_l6#Ffhn6$FSFd_l>-F
ahnFeq6$F]qFS>-Fc^lFeq&F]_lF]gl>-Fc^l6$FMFd_l&F]_l6$F]qFd_l>-Fc^l6$FM%(replaceG
&F]_l6$F]qF`jn-%*unprotectG6#-Ffu6#Fi^l>Fi^lFM-%(protectGFejn-FD6#/FM7$F\inFS6#
%jpquotrep(quotrepname,~submodule)~This|+~~~~~~~~~~~~~~~function~defines~a~quot
ient~representation.GFgjnF76#FapFVt+6$'%$VarGF,FA6*%#GLG%#ALGFinF_]m%%FlagG%#rk
G%%indxG%$rtsGFf]lF7C$@$FhrF\^l@%4-F`tFain-F_\l6$%8algebra~%1~not~defined.GFSC(
@%-F`tFc[m>F`s-Fao6$t+FgdmF7F7F7@%F_xFhdlFMF7F7F76#FfpFM>F`s-Fao6$t+FgdmF7F7F7@
%F_xFhdlFMF7F7F76#Ffp7#FM>FfnFfp>F:Fas>F]q-%%grabGF`z?(F7FfpFfpF731Ffn-FdqFb]nF
:C%>F:F%?(FiqFfpFfp-FdqF]glFas@&/&F`sFi[m&F]qFdamC$>F:Fas[333-F`t6$Fe^oFbt-F`t6
$7#-F_q6#Fe^oFhx/-F_q6$F`elFd^o-F_q6$F`elFe^o/-Fdq6#Fd^o-FdqFb_oC&>F:Fas@$-F`t6
$FSFifnC%>Fhil-&%.LinearAlgebraG6#%-RowDimensionG6#&-F_q6$F__l-Fa_l6#FifnF`z@$/
FiqFapC$>Fa`m-F_q6$FfpFd^o@$52Fa`mFfp2FhilFa`m>F:F%@$/FiqFfpC%>Fa`m7#-F_qFj_o@%
/-%*substringG6$-F^al6$-F_q6$Ffp7#&Fj`o6$FSF`t%'stringG;FfpFfpQ"AF7>Fbbm-I&root
sG6$%*protectedG%(_syslibG6#&-F^al6$-Fbbo6$-F^al6$-F_q6$FapFhboF[co;F_ilF_ilFBF
eim>Fbbm-F`co6#&-F^al6$FaboFBFeim@$45-Fj_l6$Fa`mFbbm-Fj_l6$,$Fa`mFbvFbbm>F:F%@$
-F`t6$FSF__nC%>Fhil-Fd`o6#&Fj`o6#-F\gn6$FSF^gn@$F_aoC$>Fa`mFbao@$Feao>F:F%@$Fja
oC%>Fa`m7#-F_q6$;Ffp,&Fi_oFfpFbvFfpFd^o@%/-Fbbo6$-F^al6$-F_q6$Ffp7#&Fj`o6$FgeoF
`tF[coF\coF]co>Fbbm-F`co6#&-F^al6$-Fbbo6$-F^al6$-F_q6$FapF^goF[coF^doFBFeim>Fbb
m-F`co6#&-F^al6$FhfoFBFeim@$Ffdo>F:F%Fh^o>Ffn,&FfnFfpFfpFfp-FDFg_l6#%\[lisgener
ator(Var[,algname])~checks~to~see~whether~the~passed~on~variable~or~in~|+~~~~~~
~~~~~~~~~~case~of~a~list~all~elements~in~the~list~are~generators~or~not;~search
es~through~|+~~~~~~~~~~~~~~~~the~list~GENERATORS~and~returns~true~if~found,~fal
se~if~not~foundG6#F^cmF76#FapF_clt+6#%"GG6$Fj_n%$RepGF5F7C%@'FhrF\^l/FirFap>F`s
&F]sF`p>F`sFi^l@'-F`t6$F`sFahn>F]q-%*traperrorG6#-%4mainquotrepsimplifyG6$FMF`s
-F`t6$F`sFc^l>F]q-F\jo6#-F[amF`jo-F_\l6$%hn%1~is~not~a~representation~and~not~a
~quotient~representation.GF`s@%/F]q%*lasterrorG-F_\l6#F\[p-FD6#-%*applycharGF]g
l6#%\rThis~is~an~interface~to~the~function~mainrepsimplify()~which~is~the~main~
representation~simplification~procedure.GF7F76#Ffp%*lsimplifyGt+F76#Fj_nF5F7C$>
F]q-F\jo6#-Fi`m6#F]s@%F[[pF][pF_[p6#%[qThis~is~an~interface~to~the~function~mai
nlsimplify()~which~is~the~main~simplification~procedure.GF7F76#F`el%'unienvGt+F
76%Fc_nF0FinF5F7C)Fg]l>F`sF^cm>F]qF`el?(FfnFfpFfpFirFas@%-F`t6$&F]sFi[mFd_l>F`s
F]]p>F]qF]]p@&4-F`t6$F`sFd_l-F_\l6$%;invalid~algebra~%1~to~use.GF`sFdhl>F]q(%#U
_GF`s>-Fc\pF]glF`s-FD6#-Fbgn6%F]q7#&-F_q6$F__l-Fa_l6#Fd_lFb]n&Fb^p6$F`s%'weight
G6#%coDefines~a~Universal~Enveloping~algebra~for~the~Lie~algebra~passed~to~it.G
F7F76#F`elI(versionG6$FbcoFccot+F7F7F7F7C'-F\[n6#%jp###########################
####################################################################G-F\[n6#%io
LieAlg~-~Maple~9~package~for~computations~in~infinite~dimensional~Lie~algebrasG
-F\[n6#%,Version~1.2G-F\[n6#%dq(c)~2001-2019~by~Yuly~Billig~(billig@math.carlet
on.ca)~and~Matthias~Mazzag~(matyas.mazzag@pucer.dhis.org)GF`_pF7F7F76#F`el%&del
taGt+6$'FeoF,'FfoF,F7F5F7@%5FctF]u-FD6#-Ffu6#-F]`pF^x@%/FMFS-FDFep-FD6#F`el6#%9
Krockner~delta~function.GF7F76#FapFc^lt+F76,FinF0%$GTLG%%Lz2LG%"LG%"TG%"PGFc_n%
'UniAlgG%"ZGF5F7C5Fg]l>FbbmF`el>F`sF^cm>%'lambdaG.F^bp>Ffn.Fejl>F:F\`l>Fiqf*Fgd
mF7FhoF7@%F_t@%F\^mF^bp&F^bp6#FgxF^bpF7F7F7?(F]qFfpFfpFirFas@+-F`t6$F]anFd_l>F`
sF]an5-F`t6$-Fa_lFdan%*procedureG-F`t6$FacpFN>FiqF]an-F`t6$F]anFix@%-F`t6$F]an-
Fix6#Ffem>F:F]an-F_\l6$%Vexpected~a~set~of~rules~in~the~form~x=y,~received~%1.G
F]an-F`t6$F]anFB@%/FbbmF`el>FbbmF]an>FfnF]an-F_\l6$%Yexpected~one~of~procedure,
~name~or~algebra,~received~%1.GFeio@&Fa]p-F_\l6$%;algebra~%1~is~not~defined.GF`
s30F:F\`l-Fj_l6%F%-Fao6%f*6$FeoFfoF7FhoF7-%$&!=G6$Fc`l7#-Fjp6$F`el/F]pFc`lF7F76
$FinF]q-Fao6$f*FgdmF7FhoF7F]vF7F7F7F:F`sFjdl-F_\l6%%Vreplacement~rule~%1~is~for
~a~nonzero~generator~in~%2.G&F:F]glF`s@%/F\`lF:C(>Fhil-Fi]oFb]n>Ff]mF\`l?(F]qFf
pFfp-Fdq6#FifpFas@$-Fgep6$-Fd`l6$&FhilF]glF`s7#-Fjp6$F`el/F]qFagpC%>Ff]mF\`l?(F
7FfpFfpF731F]q-FdqFeimF_gpC$>Ff]m7$&Ff]mF7Fcgp>F]qFjelFh^o@&-F`t6$F`sFifn>Ff]m7
#-Fjp6$&-F_q6$F`el&Ff]mFepF]gl/F]q;Ffp-Fd`o6#&Fj`oFb]n-F`t6$F`sF__n>Ff]mF\`l>Ff
]m-Fao6$f*FgdmF7FhoF7/FM-F]pFeqF7F76$FdapFiqFf]m>F:Fiq>Ff]mF:@%-F`t6$F`sFc\p>Fe
bmF`s>Febm-F_q6$Ffp&7#-Fc\pFb]nFep@$Fddp>Fbbm(%$HW_GFebmFcjn>Fi^lFbbmFijn@%/Ff]
mF\`l>-Fc^l6#FbbmFfn>Fa[q&Ffn6#&-Fao6$f*FgdmF7FhoF7F`vF7F7F7Ff]mF7>-Fc^l6$FbbmF
d_l6$Febm&-F_q6$F__l-Fa_l6#Fc\pFhim>-Fc^l6$FbbmF`jn-Fa_lFg_l-FD6#/FbbmFa[q6#%:D
efines~a~Representation.G6%FejlF^bpFi^lF76#F`elFbut+6$F='Fgap%,nonnegativeG6&Fi
n%%tempGF0F1F5F7@'/F`elFSF[ap/FfpFS-FDFeqC$@%Fhr@%-F`t6$F\sFd_lC$>FfnF\s>FiqFas
>FiqF%>FiqF%@+F_x@%Fiq-FD6#-Fao6&FbuFMFSFfn-FD6#-Fao6%FbuFMFSF_[lC%>F`sFM?(F]qF
fpFfp,&FSFfpFbvFfpFas@%Fiq>F`s-Fiu6%F`sFMFfn>F`s-Fiu6$F`sFM-FDFb]nF`u-FD6#-F]o6
$/Fap*&F`vFfpFSFfpFM5FJ33FctFiq4-FV6$FMFfn-FD6#)FMFS-FD6#-Ffu6#-FbuF^x6#%coOver
loaded~operator~that~represents~powers~used~in~associative~algebras.GF7F76#Fap%
+convert/&@Gt+6#'Feap-Fix6#F,6$F0F1F5F7C$@%2FfpFirC$>F]qFeio>F`sFas>F`sF%@'/FMF
\`lF\ap/FcqFfp-FD6#&FMF7@%F`s-FD6#-Fiu6%-F^al6%&FM6#;Ffp,&FcqFfpFbvFfpFiuF]q&FM
6#FcqF]q-FD6#-Ffu6#-Fiu6$-F^al6$FjbqFiuF^cq6#%VConverts~a~list~to~an~associativ
e~algebra~expression.GF7F76#FfpF`cot+6#Fd_n60%%CMatGFh_n%"mGFin%$curG%)allroots
G%)newrootsG%%zvecG%)bufrootsG%#rtG%'newvecGF_]m%&marksG%&boundG6$Fg]lF6F7@%554
F_t0FcqFfp4-F`t6$FgxF\]l-F_\l6$FbcnFMC/>F`sFgx@$/-F_q6$F`elFMF+>F]q-%&AnmatGFb]
n@$/FheqF.>F]q-%&BnmatGFb]n@$/Fheq%"CG>F]q-%&CnmatGFb]n@$/Fheq%"DG>F]q-%&DnmatG
Fb]n@$/FheqF>>F]q-%&EnmatGFb]n@$/Fheq%"FG>F]q-%&FnmatGFb]n@$/FheqF^io>F]q-%&Gnm
atGFb]n>FhilF\`l>Fa`mF\`l?(FiqFfpFfpF`sFasC%>8.7#-Fjp6$F`el/Fiq;FfpF`s>&FchqFda
mFfp>Fa`m7$F\anFchq?(F7FfpFfpF72F`elFjanC&>Fhil7$&FhilF7F\an>FebmFa`m>Fa`mF\`l?
(8/FfpFfp-FdqFhimFasC%>Ff]m&Febm6#Ffiq>80-%".G6$F]q-%'VectorG6#Ff]m?(FiqFfpFfpF
`sFasC%>F:Ff]m>81,$&F]jqFdamFbv?(FfnFfpFfpFhjqFasC$>&F:Fdam,&F^[rFfpFfpFfp@$45-
Fj_l6$F:Fhil-Fj_l6$F:Fa`m>Fa`m7$F\anF:-FD6#-Fao6$f*FgdmF7FhoF7Fb[mF7F7F7Fhil6#%
Acreates~a~list~of~positive~rootsGF7F76#Ffp%%initGt+F7F7F5F7C?-Fdjn6#-F_q6#-Fao
6$F_q7$-Fdim6#F"-Fdim6#%.LieAlg_HiddenG-Fdjn6*-FfuFjho-Ffu6#F\jl-Ffu6#%,MATRIX_
TYPEG-Ffu6#%.MATRIX_LACINGG-Ffu6#FgbmFfjn-Ffu6#%&IDEALG-Ffu6#%.USING_HISTORYG-%
%withGF^]r>FgbmF\`l>F\jlF`el>F^cm.F^cm>Fg]r.Fg]r>Fj]r.Fj]r>Fi^l.Fi^l>F_^r.F_^r>
Fb^rF\`l-%+NewAlgTypeG6#%&idealG-Fc_r6#%)KacMoodyG-Fc_rFb\q-Fc_rFb_l-Fc_rFicm-F
c_rFe^p-Fc_r6#%*directsumG-Fc_r6#%(quotalgG-Fc_r6#%+triangularG-Fc_rF]ao-Fc_r6#
F__n-Fc_rF`in-Fc_r6#Fahn-%*NewOpTypeG6#F'-F]ar6#Fiu-F]ar6#Fbu-FjjnFe\r-Fjjn6*F^
cmFc]rFg]rFj]rF[^rFi^lF_^rF`^r6#%jninitializing~function,~called~when~the~packa
ge~LieAlg~is~loadedG6*FgbmF^cmF\jlFg]rFj]rFi^lF_^rFb^rF76#F`elFiut+F)6)F0%%UAlg
G%&HwRepGF1F2F3F4F5F7C'>Fa`mt+6&F=F?'F\brFB'F]brF,F7F7F7-FD6#-FG6#5FJ33FctFS45F
U/FMFcclF7F7F76#F__l>F:t+FabrFhnF7F7-FD6#-F]o6$&-Fao6'f*6&FeoFfoFgoFjalF7FhoF7@
$-F]p6&F_pFSFXFcclOFcpF7F7FgpFhpFSFXFcclF7FMF7F76$F4Fa`m6#F__l>Fhilt+FabrFhnF7F
7-FD6#-F]o6$&-Fao6'f*FicrF7FhoF7@$4F[drOFcpF7F7FgpFhpFSFXFcclF7FMF7F7F^dr6#F__l
@%Fhr@'F[^qC%>F]qF\s>F`sF\s>FiqFasFa^lC&>F]qF\s>F`s&&F]_lF\^qFep>Ffn&F]_l6#F\s>
FiqFas>FiqF%>FiqF%@+5-Fa`m6&FMFiqF`sFfn-Fa`m6&FSFiqF`sFfnFisF_x@%-%-HasConstant
sGFeq@%Fiq-FD6#*&-FhilFbfrFfp-Fiu6%-F:FbfrFSF]qFfp-FD6#*&F\grFfp-Fiu6$F_grFSFfp
-FD6#-Ffu6#-FiuF^xFhy@%-FgfrF`z@%Fiq-FD6#*&-FhilFdfrFfp-Fiu6%FM-F:FdfrF]qFfp-FD
6#*&F`hrFfp-Fiu6$FMFchrFfpFegrF^[l@%Fiq-FD6#-Fh[l6&FMFSFiuF]q-FD6#-Fh[l6%FMFSFi
uFegr6#%[pOverloaded~operator~that~represents~multiplication~used~in~associativ
e~algebras.GF7F76#Fap%*expand/&@Gt+F)F7F5F7@%Fhr-FD6#-Fh[l6&FMFSFiuF\sF^ir6#%KE
xpands~an~associative~algebra~expression.GF7F76#Fap%$&>=Gt+Fi[nF7F5F7-FD6#4-%#&
<GF^x6#%htmonomial~&>~monomial~defines~the~operator~"&>=",~which~is~interface~t
o~the~|+~~~~~~~~~~~~~~~~~function~evaluate;~works~only~with~the~default~set~of~
generatorsGF7F76#Fap%*asimplifyGt+F7Fh[pF5F7C$>F]q-F\jo6#-Fj`mF^\p@%F[[pF][p-FD
6#-F^al6$Fa[pFbu6#%gqThis~is~an~interface~to~the~function~mainasimplify()~which
~is~the~main~associative~simplification~procedure.GF7F76#F`elFb`rt+6$Fb_n'%&Ide
alGFe_r6#%(AlgebraGF5F7C(Fg]l>F]q&-F_q6$F__l-Fa_lFd_rFain@&F[^lF\^lF_^l@%4-F`t6
$F\sFj\l-F_\l6$%`olist~of~integers~is~expected~for~the~cut~off~weight,~but~rece
ived~%1.GF\s>-Fb`r6$FM%*stablesetG6$F\s-F_]s6%7#&Fa\sF`zF\sF]q>-Fb`rFeqFdin-Fbg
n6%FM7#&Fb^pF]gl&Fb^p6$F]qFh^p-FD6#-%&usingGFeq6#%asquotalg(quotalgname,~idealn
ame,~algname(optional))~This|+~~~~~~~~~~~~~~~function~defines~a~quotient~algebr
a~of~an~ideal~and~its~algebraG6$F^cmF_^rF76#Fap%/characteristicGt+6#'%"pGF\]lF7
F5F7C$-Fe`m6#7)Fi`mFj`mF[am%*quotbasisG%/submodulebasisG%-quotrepbasisGFe\l@%Fh
aq-F_\l6$%`ocharacteristic()~expects~zero~or~one~(integer)~argument,~received~%
1.GF]sC&-Fdjn6#Fc]r>F\jlFM-FjjnFg_s-FD6#/-Ffu6#Fe^sF\jl6#%\othrough~characteris
tic()~it~is~possible~to~set~the~CHARACTERISTICGFd]rF76#FfpFejrt+Fi[nF\\nF5F7C'@
%F_[l>F]qFb\n>F]qFM@$Fhfl>F]qF\gl@%Fb[l>F`sFj\n>F`sFS@$F^]n>F`sFa]n@%Fd]n-FD6#-
FG6#2F[^nF`el-FD6#-FG6#2F[_nFi^n6#%gtmonomial~&<~monomial~defines~the~operator~
"&<",~which~is~interface~to~the~|+~~~~~~~~~~~~~~~~~function~evaluate;~works~onl
y~with~the~default~set~of~generatorsGF7F76#FapFifnt+Fa_n6(FinF_]mFg_nFh_nFi_nFj
_nF5F7C)Fg]l@%F]`nF\^lC&>Ffn7$Fa`nFb`n>F:F\`l>FhilF\`l?(F]qFZFfpFirFasC$>Fhil7$
FbiqF]an@'3F`an/FcanFap>FfnF]anF_bn>F:F]anFdbn@%FhbnF`cnC$>FiqF_z@(/-F_q6$F`elF
SF.-Fifn6%-F\gn6$FM%*_unfoldedG&Fjfq6#,&FiqFfpFfpFfpFbiq/FccsFdfq-Fifn6%Fgcs&F+
6#,&FiqFapFbvFfpFbiq/FS&Fegq6#F__l-Fifn6%Fgcs&F>6#F_ilFbiq>Ffn7$&&FfnFep6#-Fjp6
$(F[clF`s/F`s;FfpFiq&&FfnF`p6#Fcdn@%/F:F\`l>F:7$7#F_es7#-Fjp6$F`elFbes>F:7$&F:F
ep7#-Fjp6$F`el/F`s;Ffp-Fdq6#Fafs>(%#A_GFM-Fa_l6#-%*regmatrixG6'FM-F_q6$F`elF]es
-F_q6$F`elFeesFccsFiq-FD6#-Fbgn6%FMFfnF:6#%Lsupports~the~declaration~of~simple~
algebrasG6$Fa`lFc`nF76#FapFh_rt+6$Fb_n'Fe_nF,63FinF_]mFc]lFi_nFg_nFh_n%&RulesG%
(DefGensG%#LpG%#LmG%#LzG%'SerrePG%'SerreMG%&TempPG%&TempMGFj_nF[clF5F7C9Fg]l@'F
]`nF\^l/FirF__lC$>F:F\s>Fiq&F]sFedsC$>F:F\`l>FiqF\`l@'-F`t6$FS%'MatrixG>FfnFS55
5-F`t6$FSFiil-F`t6$FSFix-F`t6$FS%&arrayG-F`t6$FS%'vectorG>Ffn-F^alFfis-F_\l6$%b
oexpected~argument~of~type~Matrix~(or~matrix,~list,~array),~received~%1.GFS@%0-
Fdq6#-F^al6$-&Ff[m6#%$rowG6$FfnFfpFix-Fdq6#-F^al6$-&Ff[m6#%$colGFe[tFix-F_\l6$%
;%1~is~not~a~square~matrix.GFS>Fhil-Fd`oFi[m?(F]qFfpFfpFhilFas?(F`sFfpFfpF]qFas
@&0F]qF`s@&2F`el&FfnFcjm-F_\l6$%\o%1~is~a~positive~value~outside~the~diagonal~i
n~the~cartan~matrix.GFi\t3/Fi\tF`el4/&FfnFehmF`el-F_\l6#%gnzeros~are~not~in~a~s
ymmetrical~fashion~in~the~cartan~matrix.G3/F]qF`s4/Fi\tFap-F_\l6$%Ddiagonal~ent
ry~%1~in~cartan~matrix.G0Fi\tFap@$FhesC$>Fbbm7%%"fGFc`nFa`l>F:-Fao6%t+FeepF7F7F
7-Fao6%t+FeepF7F7F7&FSFeqF7F7F76#FapFSFMF7F7F76#FapFbbm7#-Fjp6$F]q/F]q;FfpFhil>
Ff]mFafs>Fchq&F:F`p>Febm&F:F^s@%/FiqF\`lC'-Fbgn6$-F\gn6$FM%+_free_plusGFebm>Fiq
7#-Fjp6$7#-Fjp6$F`el/F]qFchqFe`t-Fbgn6%-F\gn6$FM%&_zeroGFchqFiq?(F]qFfpFfp-FdqF
damFas>&Fiq6$F]qF]qFbv-Fbgn6%-F\gn6$FM%,_free_minusGFf]mFiqC%-Fbgn6%F[`tFebmFiq
-Fbgn6%FbatFf]m,$FiqFbv-Fbgn6%Fh`tFchq7#-Fjp6$7#-Fjp6$F`el/F]qF]q/F]qFiq@$550Fg
iqFhil0-FdqFcjqFhil0-Fdq6#FchqFhil-F_\l6$%[oincorrect~number~of~generators~for~
the~cartan~matrix~of~size~%1.GFhil>Fa`mF\`l>FfiqF\`l>F]jqF\`l?(F]qFfpFfpFhilFas
?(F`sFfpFfpFhilFas@%Ff]tC$>Fa`m7%F\an/-Ffu6#-F'6$&FebmF]gl&Ff]mF]gl&FchqF]gl/-F
fu6#-F'6$Fadt&FebmFb]n*&Fi\tFfpFgdtFfp>Fa`m7%F\an/-Ffu6#-F'6$Fadt&Ff]mFb]n,$*&F
i\tFfpF`etFfpFbv/-Ffu6#-F'6$Fadt&FchqFb]nF`elC)>Fa`m7%F\an/-Ffu6#-F'6$F_dtF`etF
`elFcet>Fa`m7%F\anFbdt/F^etFaet>FhjqFgdt>82F`et?(84FfpFfp,&FfpFfpFi\tFbvFasC$>F
hjq-Ffu6#-F'6$F_dtFhjq>Ffft-Ffu6#-F'6$F`dtFfft>Ffiq7$&FfiqF7Fhjq>F]jq7$&F]jqF7F
fft-Fe_r6%-F\gn6$FM%,_plus_idealGFfiqF[`t-Fe_r6%-F\gn6$FM%-_minus_idealGF]jqFba
t-Fb`r6$-F\gn6$FM%&_plusGF]ht-Fb`r6$-F\gn6$FM%'_minusGFbht>-Fh_rFeq-Fa_lFi[m>Fj
fsFait@$-F`t6$FMFjcm-Fi\m6$Fd]oF_`m-FD6#-Fe`r6%FM7%FghtFh`tF\itFa`m6#%!GF7F76#F
ap%*expand/&^Gt+F_]q6$Fc]qFinF5F7@%Fe]qF[ap@%FJFd`qC%>F]qFM?(F`sFfpFfpF__qFas>F
]q-Ffu6#-FiuF`q-FDF]gl6#%<Expands~a~power~expression.GF7F76#FapFj`lt+6#Fh\l60F0
Fj_n%&Temp2GFinFh_n%%bvecGF[\oF\\o%+nullweightG%&quantG%%qmaxG%$levG%%maskG%'Fb
asisGF5F7C%@'FhrF\^lFcio>F]qFeioC$>F]qF^cm@$-F`t6$F]qFc\p>F]q&F_\qF]gl@,-F`tF\j
n@$0-Fdq6#-Fd`l6$&-Fi]oF]glFepF]qFcq-F_\l6%%Oweight~%1~is~of~invalid~length~for
~algebra~%2.GFMF]q-F`t6$F]qFe_rC$>F`s&Fa\sF\jn@$0-Fdq6#-Fd`l6$&FifpFepF`sFcq-F_
\l6%%Mweight~%1~is~of~invalid~length~for~ideal~%2.GFMF]q-F`t6$F]qFahnC$>F`s&&F]
_l6$&&-F_q6$F__l-Fa_lF[arF]glFepFd_lF`p@$Fh]u-F_\l6%%inweight~%1~is~of~invalid~
length~for~quotient~representation~%2.GFMF]q-F`t6$F]qFc^lC$>F`s&F[jnF`p@$Fh]u-F
_\l6%%Vweight~%1~is~of~invalid~length~for~representation~%2.GFMF]q-F`t6$F]qFfhn
C$>F`s&&F]_l6$&F]inF\jnFd_lF`p@$Fh]u-F_\l6%%Qweight~%1~is~of~invalid~length~for
~submodule~%2.GFMF]q@9-F`t6$F]qF_`rC%>F]q&-F_q6$F__l-Fa_lF^`rF]gl>F`s7$-Fdq6#-F
d`l6$&-Fi]o6#&F]qFepFepFhau-Fdq6#-Fd`l6$&-Fi]o6#&F]qF`pFepF`bu@%30F^cqF`el0&F`s
Fep&F`sF`p@%2FfbuFebu-FD6#-Fj`l6$FMFhau-FD6#-Fj`l6$FMF`bu-FD6#7$&-Fj`l6$&FM6#;F
fpFebuFhauF7&-Fj`l6$&FM6#;FfpFfbuF`buF7-F`t6$F]qFb`r-FD6#-F^_s6$FMF]q-F`t6$F]qF
e`rC$>F`s7#-Fjp6$F`el/FiqFM@'-%$&!<GF`jo-FD6#-Fj`l6$FM&&-F_q6$F__l-Fa_lFd`rF]gl
Fep-FgepF`jo-FD6#-Fj`l6$FM&FfeuF`p-FD6#-Fj`l6$FM&FfeuF^s-F`t6$F]qF__nC$>F:-Fd`o
6#&Fj`o6#-F\gn6$F]qF^gn@%-FG6#/-F_q6$FfpF[^s7$-Fjp6$(F[blFiq/FiqF_dnF[clC$>F`s-
Fj`l6$7$&FjbqF7F`elF]gu@)/F`sF\`lFg_q/-F_q6$F`elFebu-F_q6$F`el&-Fi]oF\guFep-FD6
#7#&FchuFabq/F^cqF`el-FD6#7$&-Fao6%f*6$Fa`lF[clF7FhoF7&Fheq6$FgxFSF7F7F7F`sF^cq
F7&F^]uF^s-FD6#-Fao6%f*FeiuF7FhoF7FfiuF7F7F7F`sF^cqC$>Febm-Fien6$/F[clFfp&F[^sF
`p@%-Fgep6$Febm7#-Fjp6$F`el/Fiq;FfpFgiq-F_\l6#%goBasis~of~affine~algebra~can~no
t~be~determined~since~nullroot~has~zero~weightGC)>F]jqFfp?(F7FfpFfpF71F]jqFgiqC
$>Ff]m&Febm6#F]jq@%0Ff]mF`elFh^o>F]jq,&F]jqFfpFfpFfp@%/-Fbbo6$-F^al6$-F_q6$Ffp7
#&Fj`o6$F]guF`tF[coF\coF]co>Fbbm-F`co6#&-F^al6$-Fbbo6$-F^al6$-F_q6$FapFc\vF[coF
^doFBFg_l>Fbbm-F`co6#&-F^al6$F]\vFBFg_l>Fchq-%$maxG6#-Fao6$f*FgdmF7FhoF7-%$absG
6#F[[mF7F76$Fi[uF]jq-Fao6$f*6#FadlF7FhoF7-Fd`l6$&-F_q6$F`el&-Fi]o6#-F\gn6$F]pF^
gnFepFabqF__vF7F76$F0F]qFbbm>F`sF\`l?(Ffiq-%%ceilG6#*&,&&FMFf[vFfp*&-%%signGFcj
qFfpFchqFfpFbvFfpFf]mFbvFfp-%&floorG6#*&,&Fi_vFfpFj_vFfpFfpFf]mFbvFasC$>Fhjq-Fj
`l6$,&FMFfp*&FfiqFfpFebmFfpFbvF]gu>F`s7$&F`sF7-Fjp6$&-F_q6$F`el&FhjqFdam6$-F_q6
#F`avFfiq/Fiq;Ffp-Fdq6#FhjqFg_q-F`t6$F]qFifnC%>F:-Fd`o6#&Fj`oF]gl@%/-Fbbo6$-F^a
l6$-F_q6$Ffp7#&Fj`o6$F]qF`tF[coF\coF]co>Fbbm-F`co6#&-F^al6$-Fbbo6$-F^al6$-F_q6$
FapFgbvF[coF^doFBFg_l>Fbbm-F`co6#&-F^al6$FabvFBFg_l@%-FG6#/Fcgu7#-Fjp6$(F[clFiq
Figu@%-Fgep6$FMFjdu-FD6#7#-Fjp6$&-F_q6$F`el&F^]uF`pFdamFiguC$>F`s&-F_q6$F`elF]]
uFabq@%5-Fj_l6$FMFbbm-Fj_l6$,$FMFbvFbbm-FD6#7#F`s-FD6#F\`lC%@%-FG6#/FMFjdu>F`sF
idv>F`sF\`l?(FiqFfpFfp-FdqFb[qFasC'>Fa`m&FbbmFdam>Fhil&Fcev6#F\an@$-FG6#/FM-Fd`
l6$FhilF]q>F`s7$Fj`vFhil>Fhil&Fcev6#,$F\anFbv@$Fagv>F`sFggvFg_q-F`t6$F]qFjcmC$>
F`sF[^s@%-Fj_l6$Fas-Fao6$f*FgdmF7FhoF7-F]^mFRF7F7F7F`sC%>FfnF^]u>F`s-Fao6%f*6$%
#gwG%#rwGF7FhoF7@%-F`t6$FdpFbt-Fao6&f*6%FinFjalFaivF7FhoF7@%-Fj_l6%FMFS.Fi[o&FX
6#Fi[oF%F7F7F77#-F_q6#FdpF_pFSFdpF7F7F77#-Fjp6$7$&FfnFdam&F`sFdam/Fiq;FfpF]^oFM
@%-Fj_l6$F%-Fao6$F_qF`s-F_\l6$%Kbasis~for~algebra~%1~cannot~be~determined.GF]q-
FD6#-Fao6&f*6%%#giGFb`lFjalF7FhoF7@$3Fciv/-Fd`l6$&-F_q6$F`elFdp6#&F_pF7FSFXF^\w
F7F7F77#-Fjp6$Fejv/Fiq;Ffp-FdqFi[mF]qFM-FD6#-%+genhallmonGFeduFf\uFi\wFb]u-FD6#
-%+idealbasisGFeduFj_u-FD6#-F__sFeduFa^u-FD6#-F`_sFeduFa_u-FD6#-%)repbasisGFedu
-F_\l6$%en%1~is~not~a~supported~type~of~algebra~to~find~a~basis~for.GF]q6#%\oGe
neral~Lie~algebra~or~representation~basis~calculating~function.GF7F76#Ffp%#&=Gt
+Fi[n6$F]\nF^\nF5F7C'@%F_[l>F]qFb\n>F]qFM@$Fhfl>F]qF\gl@%Fb[l>F`sFj\n>F`sFS@$F^
]n>F`sFa]n-FD6#-FG6#/7#-%(extractGFa^n7#-Ff_wFc^n6#%gtmonomial~&=~monomial~defi
nes~the~operator~"&=",~which~is~interface~to~the~|+~~~~~~~~~~~~~~~~~function~ev
aluate;~works~only~with~the~default~set~of~generatorsGF7F76#FapI*expand/&*GFcco
t+F)F7F5F7@%Fhr-FD6#-Fh[l6&FMFSF'F\sFj[l6#%:Expands~a~Lie~expression.GF7F76#Fap
Fd`lt+6#'%%ExprGFa]l6$%+FindWeightGF0F5F7C&>F]qt+6%Fi`w%(WeightsGF06'FinF_]mF^]
l%'ResultG%(GenListGF5F7@%F_[lC%>Fiq-Fao6&f*6%Fa`lFjalFb`lF7FhoF7@%F_x-F]p6%Fhd
lFSFX-F]p6%FMFSFXF7F76$F[awF]pFfxFSFX?(F]qFapFfpF\atFas@$0Ficn&FiqF]glF_fv-FD6#
FicnC'>Fiq7#-Fjp6$F`el/F]q&FSFep@%F_x>Ffn7#-Ff_w6$FhdlFX>Ffn7#-Ff_wFW>F:-Fi]oFf
fl?(F]qFfpFfp-FdqFg_lFas?(F`sFfpFfpFh\wFas@&/&FfnFb]nFdfp@%-F]^m6$&FSF]glFB>Fiq
,&FiqFfp--Fe^m6$Fadw-F_q6#Fdfp6#-F_q6#F]dwFfp>Fiq,&FiqFfpFadwFfp3-F`t6$F]dwFbt-
F`t6$FdfpFbt@$3/-F_q6$F`elF]dw-F_q6$F`elFdfp4-F]^m6$7#FgdwFN@%F_dw>FiqFcdw>FiqF
]ew-FDFdamF7F76$F[awF]q6#FZ@$FhrF\^l@%Fcio>F`sFeio>F`sF^cm-FD6#-F]q6%FMFf^pF`s6
#%juwt(expression)~calculates~the~weight~of~a~given~expression~using~values~def
ined~|+~~~~~~~~~~~~~~~for~the~generators~in~generators();~---->~doesn't~work~fo
r~directsums~yet~<----GF\^rF76#FfpF_`rt+6$Fb_n'%%AlgsG-FixFe^p6+F`]m%(Weight1G%
(Weight2G%*DefWeightGFin%,SortByDegWtG%-SortByDegGenG%%AlgLGF[clF5F7C$Fg]l@%Fhr
F\^lC-@%/F\cnFfp>Fbbm7$&FSF7F^cm>FbbmFS>F]qFb^p>-F_`rFeq6$&FbbmFep&FbbmF`p>F`s7
#-F_q6#&F]q6$FhhwFh^p>Ffn7#-F_q6#&F]q6$FihwFh^p@%/-Fdq6#Febu-Fdq6#F]es>Fiq7$-F_
qFb]n-F_qFi[mC%@%2FjiwFhiw>Fiq7#-Fjp6$7#-Fjp6$F`el/F:;FfpFhiw/F:;Ffp,&F]^oFfpFh
\wFfp>Fiq7#-Fjp6$7#-Fjp6$F`el/F:;FfpFjiwF\[x?(F:FfpFfpF]^oFas>&FiqFg_l-%$zipG6&
f*FeepF7FhoF7,&FMFfpFSFfpF7F7F7Fj[x&F`sFg_lF`el?(F:FfpFfpFh\wFas>&Fiq6#,&F:FfpF
]^oFfp-F\\x6&f*FeepF7FhoF7F_\xF7F7F7Fc\x&FfnFg_lF`el>FhilFiq>Fa`m7$&F]q6#Fhhw&F
]q6#Fihw>-Fd_lFeq-F_qF[bn>-Fd_l6$FMFh^pFhilF]^s6#%]wdirectsum(dirsumname,~|fral
g1,~alg2|hr)~This~function~produces~a~directsum~of~two~|+~~~~~~~~~~~~~~algebras
;~calling~sequence:~~directsum([name~of~dir.sum.~alg],|frset~of~(two)~|+~~~~~~~
~~~~~~~algebras|hr)GF7F76#FapFe_rt+6$Fb_n'Fg_nF_]l6$F0FinF5F7C%Fg]l@'F[^lF\^lF_
^l>F]qF\s>F]qF^cm@'4Ff\u-F_\l6$%Jexpecting~an~algebra's~name,~received~%1.GF]q-
Fj_l6$F\`l-Fao6%f*FeepF7FhoF7Fc`lF7F7F7FSF]q-F_\l6$%Ogenerators~%1~of~the~ideal
~are~not~homogenous.GFSC(>-Fe_rFeqF_z>-Fe_rFjinF]q-Fdjn6#F]^r>F_^rFM-FjjnFe_x-F
D6#Fj`p6#%enideal(idealname,~idealgens)~let's~the~user~define~an~idealGF^^rF76#
FapF`^st+F7F7F5F7C$@$2F`elFir@&-F`t6$&F]sFepFd_lC'-Fdjn6%F[^rFb]rF`^r>Fb^r7$F^c
mFb^r>F^cmFd`x>Fgbm7#&Fb^pFjho-FjjnFg`x3/Fd`x%&resetG0Fb^rF\`lC'Ff`x>F^cm&Fb^rF
ep>FgbmF\ax>Fb^r&Fb^rF`pF^ax@+3F``x/Fd`x%)showgensG-FD6#/F^cmFgbm-F`t6$F^cmF_`r
-FD6#/F^cm7#&F\auFjho-F`t6$F^cmFb`r-FD6#/F^cm7#&-F_q6$F__l-Fa_lFa`rFjho-F`t6$F^
cmFe`r-FD6#/F^cm7#&FgeuFjhoF]bx6#%arusing(algname)~changes~the~algebra~currentl
y~in~use~to~the~specified~(sets~|+~~~~~~~~~~~~~~~GENERATORS~to~that~algebra)G6%
FgbmF^cmFb^rF76#F`el%$&<>Gt+Fi[nF7F5F7-FD6#4-Fa^wF^x6#%htmonomial~&=~monomial~d
efines~the~operator~"&<>",~which~is~interface~to~the~|+~~~~~~~~~~~~~~~~~functio
n~evaluate;~works~only~with~the~default~set~of~generatorsGF7F76#Fap%+convert/&^
Gt+6#'Fa`lF,6)FeapFin%"RGFfapF_]mF0F1F5F7C$@%FhaqC$>FhilFeio>Fa`mFas>Fa`mF%@%FJ
Fg]q@'F_[l@%Fa`m-FD6#-Fao6%t+FeepF7F7F7@%F_x*&FdelFfp-Fedx6$FhdlFSFfp-FedxF^xF7
F7F76#FapFMFhil-FD6#-Fao6$t+FgdmF7F7F7@%F_x*&FdelFfp-Fedx6#FhdlFfp-FedxFeqF7F7F
76#FfpFMF_x@%Fa`m-FD6#*&FdelFfp-Fedx6$FhdlFhilFfp-FD6#FefxC'@%Fg\o>F]qFM>F]q7#-
%&allopG6$FM%*keeptermsG>FfnF`el>F`sFfp?(F7FfpFfpF71F`sFa^oC'>Fiq&F]qFb]n>F`sF]
hl>F:Ffp?(F7FfpFfpF73F^hx/FiqFahxC$>F:Fben>F`sF]hl@%0FfnF`el@%Fa`m>Ffn-Ffu6#-Fi
u6$Ffn-FbuFeem>Ffn-Ffu6#-Fiu6$Ffn-Fbu6%FiqF:Fhil>FfnFbix-FDFi[m6#%ctSimplifies~
an~associative~multiplication~expression~by~writing~where~possible~'&^'~for~the
~same~terms~in~sequence.~For~example:~input:~e&@e~output:~e&^2GF7F76#FfpFbgnt+6
$Fb_n'Fg_nFix6(%&DefwtGFinFj_nFhgwFigwF[clF5F7C*@$F[^lF\^l@%F_^l@%4-F`t6$F\sFab
n-F_\l6$%<expected~list,~received~%1.GF\sC$?(F`sFfpFfp-FdqF[frFas@$1FapF`s@$0-F
dq6#&F\s6#Fggl-Fdq6#&F\sFb]n-F_\l6%%Kweights~%1~and~%2~are~of~different~length.
GFg[yF[\y>F]qF\s>F]q7#-Fjp6$7%-Fjp6$F`el/F`sFfglFfp-Fjp6$F`el/F`s;F]hlF\cn/F`s;
FfpF\cn@%34-F]^m6$F]qFB-Fj_l6$F%-Fao6%f*6$Fa`lFa^tF7FhoF7-FG6#/FSFMF7F7F7&F]q6#
;FapFa^oFhauC&>Ffn7#-Fjp6$7$F`s&FahxF7/F`s;FfpFa^o>Fiq-%%sortG6$Ffn%%&!!<G>F:-F
ao6&t+FdoF7F7F7@$-Fj_l6%FMFS.F]p&FXF\[mF7F76$F[clFhil6#FZFiqFfnFS>Fiq7#-Fjp6$&F
`s6#;FapF]^o/F`sFiqC$>FiqF]q>F:FS>Fb]x-F_qFg_l>Fe]xFiq-Fe_r6%FMF:FMF_^s-FD6$Fj`
pF]q6#%izgenerators(algname,~|frgenerators|hr[,[weights]])~uses~its~remember-ta
ble~to~store|+~~~~~~~~~~~~~~~the~different~sets~of~generators~in~a~table~form;~
everytime~a~new~set~of~|+~~~~~~~~~~~~~~~generators~is~added,~the~list~GENERATOR
S~is~set~to~that~list~by~defaultG6$FgbmF^cmF76#Fap%+convert/&*Gt+6#'FeapFhxF7F5
F7-FD6#-%*listtolieG6$-%+lieconvertGFd\nF^cm6#%RConverts~a~list~to~a~free~Lie~a
lgebra~expression.GF7F76#FfpFe`rt+6$Fb_n'F^]lFhx65FinF_]mF[clF`]m%#WpG%#WhG%#Wn
G%#GpG%#GnG%#GhGFj_nFchs%#LnG%"HG%$LenG%(EntriesGFhgwFigwFcjxF5F7C%Fg]l>FiqFb^p
@$0FiqF[dmC8@%33-Fj_l6$7#F]cw7#-FdimFdam-Fj_l6$7#&FSF`pFecy-Fj_l6$7#&FSF^sFecy@
'/&&Fiq6$F]cwFh^pFep7#-Fjp6$F`el/F]qFadyC$>FhjqF]cw@%-%%&!<=G6$&&Fiq6$FjcyFh^pF
ep7#-Fjp6$F`el/F]qF^eyC$>F]jqFjcy>FfiqF^dyC$>FfiqFjcy>F]jqF^dy/F^eyFaeyC$>FhjqF
jcy@%-F\ey6$FadyFddyC$>F]jqF]cw>FfiqF^dyC$>FfiqF]cw>F]jqF^dyC$>FhjqF^dy@%F_fyC$
>F]jqF]cw>FfiqFjcyC$>FfiqF]cw>F]jqFjcy-F_\l6$%fnone~of~the~algebras~from~%1~is~
not~defined~in~generators().GFS>F:&Fiq6$FfiqFh^p>FfftFgfs?(F]qFfpFfpFicwFas@&-F
]^m6$Fdfp%)negativeG-F_\l6#%Onegative~weight~%1~is~not~allowed~for~algebra.G0-F
dqFhdwFfft-F_\l6%%Jweights~%1~and~%2~have~different~lengths.GFafsFdfp>Fhil&Fiq6
$FhjqFh^p?(F]qFfpFfpF]hpFas@&-%%&!<>G6$Fcgp7#-Fjp6$F`el/F]qFcgp-F_\l6$%Nonly~ze
ro~weights~are~allowed~for~algebra~%1.GFhjq0-Fdq6#FcgpFfft-F_\l6%FchyFafsFcgp>F
a`m&Fiq6$F]jqFh^p?(F]qFfpFfpFjanFas@&-F]^m6$&Fa`mF]gl%)positiveG-F_\l6$%Opositi
ve~weight~is~not~allowed~for~algebra~%1.GF]jq0-Fdq6#F_jyFfft-F_\l6%FchyFafsF_jy
@$F_^l@%-F`t6$F\sFix-Fi\m6$7$&F\sF7FMF_`m-F_\l6$%Krules~are~expected~in~a~list,
~received~%1.GF\s>Fbbm7#&FiqF[jq>Febm7#&FiqFf[v>Ff]m7#&FiqFgav>FiqFfcm@%3F]cy-F
j_l6$Fd]oFecy>83&FiqFeq>Fc\zF\`lF_[n?(F]qFfpFfpFifvFas?(F`sFfpFfpFgiqFas@$/-Fh`
m6$-Ffu6#-F'6$&FbbmF]glFgdtFMFfhm@&0-Fd`l6$F`]zFfiq,$-Fd`l6$FgdtF]jqFbv-Fi\m6$7
$/F\]zF`elFMF_`m/Fc]zFe]zC$>Fchq-%)readstatG6#-F\gn6&-F^al6$F`]zF[coF'-F^al6$Fg
dtF[co%$~=~G-Fi\m6#7$/F\]zFchqFM?(F]qFfpFfpFjbtFasC%?(F`sFfpFfpFifvFas@$/-Fh`m6
$-Ffu6#-F'6$F`dt&FbbmFb]nFMFfhmC$>Fchq-F`^z6#-F\gn6&-F^al6$F`dtF[coF'-F^al6$Fh_
zF[coFh^z-Fi\m6#7$/Fd_zFchqFM?(F`sFfpFfpFgiqFas@$/-Fh`m6$-Ffu6#-F'6$F`dtFgdtFMF
fhmC$>Fchq-F`^z6#-F\gn6&F_`zF'Ff^zFh^z-Fi\m6#7$/F\azFchqFM?(F`sF]qFfpFjbtFas@$/
-Fh`m6$-Ffu6#-F'6$F`dtF`etFMFfhm-Fi\m6$7$/F_bzF`elFMF_`m@%-F]^m6$7%&F:F7FbiqF\a
nFBC$>FhftFjbz>857%&FbbmF7Fahp&FebmF7C&>867#-Fjp6$7$&&FjbzF]glF7F]q/F]q;Ffp-Fdq
6#Fjbz>Fhft-Fj^y6$FeczF`eu>F_cz-Fao6&t+FdoF7F7F7@$Fb_yFe_yF7F76$F[clFfn6#FZFecz
FhftF`cz>Fhft7#-Fjp6$&F]q6#;Ffp,&Fa^oFfpFbvFfp/F]qFhft>Fb]x-F_q6#F_cz>Fe]xFhft>
-Fe`rFeq6%F]jqFhjqFfiqF]^s6#%\oallows~the~construction~of~algebras~with~triangu
lar~decompositionGF7F76#Fap%+dotproductGt+6$'%#elGFa]l'%#erGFa]l6.F__mF[bl%#LIG
%#RIGF0Fc]l%'LacingG%%TypeG%#UEG%#UMGFa`l%%SizeGFidqF7C%@)F[^lF\^l3Fhr-F`t6$F\s
Fifn>F:F\s-F`t6$F^cmFifn>F:F^cmC$@%F_^l>F:F\s>F:F^cm-F_\l6$%aodotproduct~is~def
ined~for~simple~algebras,~%1~is~not~a~simple~algebra.GF:>Fchq-Fa_l6#-Fh[l6&-Ff[
pF[al-Ff[p6$FSF:F'F:@+/FchqF`elF\ap-F`t6$FchqFa[l-FD6#-Fao6%t+FeepF7F7F7@%F_x*&
F]vFfp-F]fz6%-F_q6$FfpF`v-F_q6$FapF`vFSFfp-F]fz6%F]vF`vFSF7F7F76#FapFchqF:-F`t6
$FchqFax-FD6#*&-F_q6$FfpFchqFfp-F]fz6%-F_q6$Ffp-F_q6$FapFchq-F_q6$FapFcjzF:Ffp0
-Fdq6#7#-Ff_w6$FchqF:Fap-F_\l6$%I%1~contains~invalid~terms~in~dotproduct.GFchqC
+>FcjmF[[[l>Ffn7#-F_qF]gl>Fiq7#F^jw>Fhil&Fj`oFg_l>Fido&Fj`o6$F:F`t>Ffiq-Fd`oFei
m@)5-F`t6$Ffn%(mixedwtG-F`t6$FiqFb\[lF\ap3/-F_q6$F`el&FgbmF`p-F_q6$F`elF]q/Fg\[
l-F_q6$F`elF`s@'5552&FfnF7Ffp2FfiqFd][l2&FiqF7Ffp2FfiqFg][lF\ap/Fa`m%+ADE_matri
xG-FD6#&Fhil6$Fd][lFg][l>Febm-(%)unfoldh_GFa`m6$FchqFfiq5Ff\[lF\][lF\ap@%Fi][l@
%0FfnFjatF\ap-FD6#)Fbv-(%)epsilon_GFbbm6%FfnFiqFhil>Febm-(%(unfold_GFa`mF\[[l>F
:-F\gn6$F:Fics@)-FK6$FebmFN-FDFhim-F`t6$FebmFa[l-FD6#-Fao6%t+FeepF7F7F7@%F_xF^i
zFeizF7F7F76#FapFebmF:-F`t6$FebmFax-FD6#*&-F_q6$FfpFebmFfp-F]fz6%-F_q6$Ffp-F_q6
$FapFebm-F_q6$FapF^a[lF:Ffp-FD6#-F]fz6%Fh`[lF^a[lF:6#%[oComputes~the~dotproduct
~(scalar~product)~for~ADE~simple~agebras.GF7F76#FapFfhnt+F[^x6%F`io%)RealGensG%
*SplitGensGF5F7C&Fg]l@'F[^lF\^lF_^l>F]qF\s>F]qFi^l>F`s-Fao6%f*6$%"gGFb`lF7FhoF7
@$0F`el-F_clF^xFMF7F7F7FSF]q@%4Fa_u-F_\l6$%Nexpecting~a~representation~name,~re
ceived~%1.GF]qC%>F`s-Fao6%f*Feb[lF7FhoF7@$Fhb[lFMF7F7F7FSF]q>Ffn-Fao6$f*6#Ffb[l
F7FhoF7@%F_[lFgxFMF7F7F7F`s@%-Fj_l6$F\`l-Fao6&f*6%Ffb[lF[blFb`lF7FhoF7-Fd`l6$-F
a_l6#-Fien6$/FSFfpFMFXF7F7F7FfnFginFe_u-F_\l6$%Sgenerators~%1~of~the~submodule~
are~not~homogenous.GFSC%>-FfhnFeqF^jw>-FfhnFjinF]q-FD6#/FMF`s6#%dosubmodule(sub
modulename,~submodulegens)~let's~the~user~define~a~submoduleGF7F76#FapF7
