M7R0
I.LieAlg_Hidden=6"%&falseGE\[lep%6type/G_matrix_truegenGt+6#'%#giG-%%listG6#%(i
ntegerG6"6#%fnCopyright~(c)~2001-2004~by~Yuly~Billig~and~Matthias~Mazzag.GF0-%'
memberG6$9$7.7$"""""!7$F:F97$F9F97$""#F97$""$F97$F@F>7$!""F:7$F:FC7$FCFC7$!"#FC
7$!"$FC7$FIFG6#%ZDefines~the~indices~of~true~generators~for~g[2]~algebras.GF0F0
6#F9%-HasConstantsGt+6#'%"GG%*algebraicG6%%"iG%%termG%'ResultGF0F0C%>8&F%@%-%%t
ypeG6$F6%"*G?(8$F9F9-%%nopsG6#F6%%trueGC$>8%-%#opG6$F[oF6@$-%#isG6$Fbo%)constan
tG>FZF_o-%&ERRORG6#%Kargument~of~PickConstants~is~not~a~productG-%'RETURNG6#FZF
0F0F06#F9%+genhallmonGt+6#'%'WeightGF,6'%$AddGFW%-dogenhallmonG%$AlgGFU6$%)reme
mberGF2F0C)>FZt+6%FhpFjpF\q6&%$SetGFU%"AG%"BG6%F^q%'systemGF2F0C&>8'7#-%$seqG6$
F:/FboF6>F[o7"?(F0F9F9F00F[rF6C$?(FboF9F9-F]o6#F[rF_o@%/&F[r6#Fbo&F6F\s>F[sF:C$
@%9%>F[s,&F[sF9F9F9>F[s,&F[sF9FCF9[@$Fdr>F[o7$&F[oF0&-%$mapG6&f*6%%"uG%#vlG%"aG
F06$%)operatorG%&arrowGF0&-F]t6&f*6%%"vGFatFctF0FdtF0@$3-%#&<G6$FasF65-%,isgene
ratorG6$F69&3-Fgn6$F6%#&*G-%$&>=G6$Fas-Fdo6$F9F6-%&evalnG6#-FjuFauF0F0F0FasF6Ff
uF0F0F0F0-T#6%,&F6F9F[rFCFasFfu-Fev6%F[rFasFfu%(ALGEBRAGF0-Fap6#7$Fjs&-F]t6&f*6
%%"gGFct%"wGF0FdtF0@$/-%#wtG6$F6FasFfuF6F0F0F0%+GENERATORSGFjvF6F06#%RGenerates
~Hall~Monomials~of~the~specified~degree.G6$FjvFjw6$F[qFZ6#F@@'2F>9#-F]p6$%7too~
many~arguments~%1.G9"/FbxF>>F[r&Ffx6#F>>F[rFjv@'-Fgn6$F6%(mixedwtG-Fap6#Fbr-%%&
!>=G6$F67#-F^r6$F:/8(F6>F[oF_o>F[oF%-%&usingGFhr>Fbo-FZ6%F6F[oF[r-F]z6#%&resetG
-FapF\s6#%9Wrapper~to~dogenhallmon.GF0F06#F9%&Cn2AnGt+6#'%"LGF,6*FU%"jG%&StateG
%&zerosG%%onesG%%twosG%$zteG%%TempGF]qF0C&>8+7$7#-F^r6$F:/F[o;F9,&F\oF>FCF9Fi[l
>FZF[r?(FboF9F9F\oF_o@13/F]sF:5/FZF[r/FZ8*C$>&&Fg[l6#F9F\sF:>&&Fg[lFjx6#,(-F]o6
#F_]lF9F9F9FboFCF:3Fc\l/FZFiyC%>FZFg\l>Fj\lF:>F^]lF:3/-%$absG6#F]sF9Fe\lC%>FZFi
y>Fj\lF]s>F^]lF]s3F[^lFe]lC$>Fj\lF]s>F^]lF]s33F[^l/FboF\o/FZ8)C$>Fj\lF]s>F^]lF]
s330FboF\o/F\^lF>5Fe]lFe\lC'>FZF[_l>Fj\l,$F]s#F9F>>&F_]lF\sFg_l>&F[]l6#,(-F]o6#
F[]lF9F9F9FboFCFg_l>F^]lFg_l3F`_lFj^lC&>Fj\lFg_l>Fj_lFg_l>F\`lFg_l>F^]lFg_lF`y-
Fap6#Fg[l6#%crChecking~for~indices~to~be~the~right~sequence~(0's,~1's,~2's,~1)~
and~unfolding~Cn~betas~into~An~alphas~at~the~same~time.GF0F06#F9%%&!<=Gt+6$'Feq
F-'FfqF-F0F1F0-Fap6#-%&evalbG6#5-%+comparewtsG6%F6%"<GFas/F6Fas6#%fqlist~&!<=~l
ist~defines~the~operator~"&!<=",~which~is~interface~to~the~|+~~~~~~~~~~~~~~~~~f
unction~comparewtsGF0F06#F>%.PickConstantsGt+FP6%FUFV%&ConstGF0F0C%>FZF9@%Ffn?(
F[oF9F9F\oF_oC$>FboFco@$Fgo>FZ*&FZF9FboF9F\pF`pF0F0F06#F9%(extractGt+6$'%"EG%)a
nythingG'F\q%(algebraG6#FUFgqF0@-55Ffn-Fgn6$F6%"+G-Fgn6$F6%#&@G-Fap6#&-F]t6%t+6
$%"xG%"yGF0F0F0-F^cl6$F6&FasF0F0F0F06#F>7#-FdoF^o7#&Ffx6#;F>FbxF0Fhu@%/FbxF@-Fa
pF^o-Fap6#&-F]t6%t+FfdlF0F0F0FidlF0F0F06#F>F]elF_elF0-Fgn6$F6%#&^G-Fap6#-F^r6$-
F^cl6$F^vFas/F[o;F9-Fdo6$F>F6-Fho6$F6Fjo-Fap6#%%NULLG-FduFiwFeel-F]p6%%C%1~is~n
ot~a~valid~generator~in~%2.GF6Fas6#%fvextract(expression)~picks~out~all~the~gen
erators~from~a~given~non-commutative~|+~~~~~~~~~~~~~~~~expression~and~returns~t
hem~in~a~list;~side~effects:~ignores~constants~inside~the~expressionGF0F06#F>%&
allopGt+6#FaclFfcl6$F^qFhqF0@)55/F\oF9-Fgn6$F6%(indexedG3FgxFhuFeelF]fl-Fap6#-F
^r6$F^vFfflFgx-Fap6#&-F]t6$f*6#FgdlF0FdtF0-Ffgl6$F6%*keeptermsGF0F0F0F]elF0-Fap
6#&-F]t6$FfglF]elF0F0F0F06#F9%8simplefunction_G_matrixGt+6$'FbclFS'%"MG%'Matrix
G6&%#LIG%#RIG%$LhsG%$RhsGF1F0@%4Fhu@%53/-Fdo6$F:F6-Fdo6$F:&FjwFjx-Fgn6$F]el%)ht
ruegenG3/Fhjl-Fdo6$F:&FjwF\]l-Fgn6$F]el%1G_matrix_truegenGFeel-Fap6#F:C$@%/F:*&
-FfilFeflF9-Ffil6$FhflFasF9Fh[mC&>FZF^v>F[rFhfl>F[o7#-FdoFbp>Fbo7#-FdoFhr@)3/Fj
jl-Fdo6$F:FZ/Fjjl-Fdo6$F:F[rFh[mF\]m-Fap6#*&-%$addG6$*&&Fbo6#F^[lF9&Fas6$FjsF^[
lF9/F^[l;F9-F]oF\sF9&Fb[m6#&FboF0F9F_]m-Fap6#,$*&-Ff]m6$*&&F[oFj]mF9&Fas6$Fb^mF
^[lF9/F^[l;F9-F]o6#F[oF9&Fb[m6#FjsF9FC-Fap6#-%&G22G2G6$F6Fjv6#%]qthis~is~the~fu
nction~for~a~simple~lie~algebra,~that~does~the~simplification~of~algebras~of~ty
pe~G2GF0F06#F>Fialt+6%'%#W1GF-'%#OPG%'symbolG'%#W2GF-FfclF1F0C%@&0F\o-F]o6#Ffu-
F]p6%%hnthe~weights~%1~and~%2~are~of~non-equal~length,~can't~compare.GF6Ffu4-F4
6$Fas<'F[bl%#<=G%"=G%">G%#>=G-F]p6$%?operation~%1~is~not~supported.GFas?(F[oF9F
9F\oF_o@(43-Fgn6$&F6F`_mF/-Fgn6$&FfuF`_mF/-Fap6#F%53/FasF[bl2F`bmF]bm3/FasFbam2
F]bmF`bmFabm53FebmFibm3FhbmFfbm-Fap6#F_oFabm6#%^ochecks~for~W1~to~be~less~than~
or~equal~to~W2~in~lexicographic~orderGF0F06#F@%+idealbasisGt+6#'Fhp%(homogwtG6)
%&isposG%.GenerateBasisG%&IdealG%&TableG%*IdealGensG%(AlgGensGF\qF]qF0C(>Fbot+6
'FhpF\dmF]dmF\q%$NegG6&FU%"WGFd[lFWFgqF0C&>F[r<"?(F[oF9F9Fg`mF_oC$>Fbo-%$zipG6&
f*FfdlF0FdtF0,&F6F9FasFCF0F0F0F6-Fhw6$F`bm9'F:@&39(4-%(hastypeG6$Fbo%)negativeG
C$>FZ-Fev6'FboFasFfuFbemFeem>F[r-%&unionG6$F[r<#-Fdo6#-F]t6%t+FfdlF0F0F0F`vF0F0
F06#F>FZF`bm45Feem-Fhem6$Fbo%)positiveGC$>FZF]fm>F[r-Fafm6$F[r<#-Fdo6#-F]t6%t+F
fdlF0F0F0F`vF0F0F06#F>FZF`bm?(F[oF9F9-F]o6#FasF_o@$/F6-Fhw6$&FasF`_mFbem>F[r-Fa
fm6$F[r<#Fbhm-Fap6#-%,independentG6$Fh\mFbemF0F06$FicmFbo6#""&@'FaxFcx3Fgx-Fgn6
$Fix%&idealG>FZFix>FZ%&IDEALG>Fg\l&-Fdo6$""%-%%evalG6#Fcim6$FZFecl>F[_l7#&-Fdo6
$F[jm-F]jm6#Fecl6#Fg\l>Fiy7#&FiimFbp@%-Fcy6$F67#-F^r6$F:/FUF6@%/-F]t6%t+FfdlF0F
0F0@$-F]al6$Fgw7#-F^r6$F:/FUFgwFabmF0F0F06#F>F[_lFg\lFbr-Fap6#-Fbo6'F6FiyF[_lFg
\lF_oF`y@%/-F]t6%t+FfdlF0F0F0@$-FcyFi[nF%F0F0F06#F>F[_lFg\lFbr-Fap6#-Fbo6'F6Fiy
F[_lFg\lF%F`y6#%hoidealbasis([weight])~generates~the~basis~of~an~algebra~for~a~
specified~weightG6#FfimF06#F9Ff_mt+F06%Fct%"bGF\qF1F0C$F^q@'FdelCao>F[o&FfxF\]l
>FboFix>FZ&Ffx6#F@>-Ff_m6$-Fav6#-Fju6$&F[o6$F9F:&F[o6$F:F9FZ&F[o6$F9F9>-Ff_m6$-
Fav6#-Fju6$Ff^nFj^nFZ&F[o6$F>F9>-Ff_m6$-Fav6#-Fju6$Ff^nFc_nFZ&F[o6$F@F9>-Ff_m6$
-Fav6#-Fju6$Ff^nF\`nFZF:>-Ff_m6$-Fav6#-Fju6$Ff^n&F[o6$F@F>FZF:>-Ff_m6$-Fav6#-Fj
u6$Ff^n&F[o6$FCF:FZ&FboF\]l>-Ff_m6$-Fav6#-Fju6$Ff^n&F[o6$F:FCFZF:>-Ff_m6$-Fav6#
-Fju6$Ff^n&F[o6$FCFCFZ,$F_bnF@>-Ff_m6$-Fav6#-Fju6$Ff^n&F[o6$FGFCFZ,$FhbnF[jm>-F
f_m6$-Fav6#-Fju6$Ff^n&F[o6$FIFCFZ,$FbcnF@>-Ff_m6$-Fav6#-Fju6$Ff^n&F[o6$FIFGFZF:
>-Ff_m6$-Fav6#-Fju6$Fh^nFj^nFZF:>-Ff_m6$-Fav6#-Fju6$Fh^nFc_nFZF:>-Ff_m6$-Fav6#-
Fju6$Fh^nF\`nFZF\an>-Ff_m6$-Fav6#-Fju6$Fh^nF\anFZF:>-Ff_m6$-Fav6#-Fju6$Fh^nFean
FZF:>-Ff_m6$-Fav6#-Fju6$Fh^nF_bnFZ&FboFjx>-Ff_m6$-Fav6#-Fju6$Fh^nFhbnFZ,$FeanFC
>-Ff_m6$-Fav6#-Fju6$Fh^nFbcnFZF:>-Ff_m6$-Fav6#-Fju6$Fh^nF\dnFZF:>-Ff_m6$-Fav6#-
Fju6$Fh^nFfdnFZF\dn>-Ff_m6$-Fav6#-Fju6$Fj^nFc_nFZ,$F\anFC>-Ff_m6$-Fav6#-Fju6$Fj
^nF\`nFZF:>-Ff_m6$-Fav6#-Fju6$Fj^nF\anFZF:>-Ff_m6$-Fav6#-Fju6$Fj^nFeanFZ,$Fh^nF
I>-Ff_m6$-Fav6#-Fju6$Fj^nF_bnFZFf^n>-Ff_m6$-Fav6#-Fju6$Fj^nFhbnFZ,&FbgnFIFganFC
>-Ff_m6$-Fav6#-Fju6$Fj^nFbcnFZ,$FeanF[jm>-Ff_m6$-Fav6#-Fju6$Fj^nF\dnFZF:>-Ff_m6
$-Fav6#-Fju6$Fj^nFfdnFZF^dn>-Ff_m6$-Fav6#-Fju6$Fc_nF\`nFZF:>-Ff_m6$-Fav6#-Fju6$
Fc_nF\anFZF:>-Ff_m6$-Fav6#-Fju6$Fc_nFeanFZ,$Fj^n!"%>-Ff_m6$-Fav6#-Fju6$Fc_nF_bn
FZF:>-Ff_m6$-Fav6#-Fju6$Fc_nFhbnFZ,$Ff^nFi^o>-Ff_m6$-Fav6#-Fju6$Fc_nFbcnFZ,&Fbg
n"#7Fgan"")>-Ff_m6$-Fav6#-Fju6$Fc_nF\dnFZ,$Fean!#7>-Ff_m6$-Fav6#-Fju6$Fc_nFfdnF
Z,$FhbnFa`o>-Ff_m6$-Fav6#-Fju6$F\`nF\anFZF:>-Ff_m6$-Fav6#-Fju6$F\`nFeanFZ,$Fc_n
FI>-Ff_m6$-Fav6#-Fju6$F\`nF_bnFZF:>-Ff_m6$-Fav6#-Fju6$F\`nFhbnFZF:>-Ff_m6$-Fav6
#-Fju6$F\`nFbcnFZ,$Ff^nFa`o>-Ff_m6$-Fav6#-Fju6$F\`nF\dnFZ,&Fbgn!#OFganFado>-Ff_
m6$-Fav6#-Fju6$F\`nFfdnFZ,$F_bn"#O>-Ff_m6$-Fav6#-Fju6$F\anFeanFZF:>-Ff_m6$-Fav6
#-Fju6$F\anF_bnFZ,$F\`nFC>-Ff_m6$-Fav6#-Fju6$F\anFhbnFZFbbo>-Ff_m6$-Fav6#-Fju6$
F\anFbcnFZ,$Fj^nF[ao>-Ff_m6$-Fav6#-Fju6$F\anF\dnFZ,$Fh^nFado>-Ff_m6$-Fav6#-Fju6
$F\anFfdnFZ,&Fbgn"#sFganFjdo>-Ff_m6$-Fav6#-Fju6$FeanF_bnFZFhbn>-Ff_m6$-Fav6#-Fj
u6$FeanFhbnFZFbcn>-Ff_m6$-Fav6#-Fju6$FeanFbcnFZF\dn>-Ff_m6$-Fav6#-Fju6$FeanF\dn
FZF:>-Ff_m6$-Fav6#-Fju6$FeanFfdnFZF:>-Ff_m6$-Fav6#-Fju6$F_bnFhbnFZF:>-Ff_m6$-Fa
v6#-Fju6$F_bnFbcnFZF:>-Ff_m6$-Fav6#-Fju6$F_bnF\dnFZFfdn>-Ff_m6$-Fav6#-Fju6$F_bn
FfdnFZF:>-Ff_m6$-Fav6#-Fju6$FhbnFbcnFZ,$FfdnFC>-Ff_m6$-Fav6#-Fju6$FhbnF\dnFZF:>
-Ff_m6$-Fav6#-Fju6$FhbnFfdnFZF:>-Ff_m6$-Fav6#-Fju6$FbcnF\dnFZF:>-Ff_m6$-Fav6#-F
ju6$FbcnFfdnFZF:>-Ff_m6$-Fav6#-Fju6$F\dnFfdnFZF:3Fgx/-F]o6#Fj]nF>C$>6$F[oFbo-Fd
oFg^p@%3-Fgn6$7#-FdoF`_mFg[m-Fgn6$7#-FdoF\sFg[m-Fap6#,$-Ff_m6$-Fav6#-Fju6$FboF[
oFixFCFh[m-Fap6#%%FAILG6#%@this~is~for~looking~up~G2~rulesGF0F06#F:%/indexedran
kingGt+6$'%)MonomialGFSFdcl6%F\[l%"pGFUF]qF0C%>%$LRPG.F^ap>F[o-F]t6't+6&%"eGFct
Fcw%#sgGF0F0F0@&3F^hl-F46%FhjlFbem.Fev6%&FgwF0FevF^el-F46%F6FfuF[bp6$F]bpFevF0F
06$F[apFbo6#F[jm7#-F^clFiwFasFjw-F]t6$f*6#%#geGF0FdtF0@%F^hlFhjlF6F0F0F0Fjw-Fap
6#-%'expandG6#-F]t6$F\dl-F^r6$*&&F[oFbpF9)F^apFZF9/FZF^_m6#%hogives~a~numerical
~rank~to~a~monomial;~to~be~used~for~comparison~of~monomials;G6#F^apF06#F>%&Bn2D
nGt+Fjz6)F^[lFd[lF_[lF`[lFa[lFb[lFc[lF]qF0C'>Fbo7#-F^r6$F:/F[o;F9F\o>FZF[r?(F[o
F9F9F\oF_o@/3/F]bmF:Fd\l>&FboF`_mF:3FjdpFe]lC$>FZFg\l>F\epF:3/-F]^l6#F]bmF9Fe\l
C$>FZFiy>F\epF]bm3FbepFe]l>F\epF]bm3/FcepF>Fe]lC$>FZF[_l>F\epF]bm3F[fpFj^l>F\ep
F]bmF`y@)Ff\l>Fbo7$7$Fb^mF:FbrFe]l>Fbo7$Fdfp7%&&Fbo6#;F9,&F_^mF9FCF9F0F:&Fbo6#F
_^mFj^l>Fbo7$7%Fhfp,$F]gpFh_lFbgpFbr>FboFbrFdz6#%`qChecking~for~indices~to~be~t
he~right~sequence~and~unfolding~Bn~betas~into~Dn~alphas~at~the~same~time.GF0F06
#F9%*applycharGt+6#'%%ExprGFSF0F1F0@%0%/CHARACTERISTICGF:@'Fjcl-Fap6#-F]t6%f*Ff
dlF0FdtF0@%Ffn*&-%$modG6$-%'NormalG6#-F`blF^oFasF9-%)PickTermGF^oF9*&-Fhhp6$-F[
ipF\]lFasF9F6F9F0F0F0F6F^hpFfn-Fap6#*&-Fhhp6$FjhpF^hpF9F^ipF9-Fap6#*&-Fhhp6$Fci
pF^hpF9F6F9Feel6#%Rapplies~characteristic~p~if~there~was~one~definedG6#F^hpF06#
F9%-type/homogwtGt+6#'%$wtsGF,F0F1F04F]y6#%DDefines~the~homogenous~weight~type.
GF0F06#F9%(matbaseGt+6$'%"nGF/'%&uplimGF/6%F^[l%"kGF[jlF1F0C%>FZ7#-F^r6$7#-F^r6
$F:/F[o;F9F6F\\q?(F[oF9F9FasF_o?(FboF9F9FasF_o@&/F[oFbo>&FZFj^pF>/-F]^l6#,&F[oF
9FboFCF9>Fc\qFC-Fap6#-%(convertG6$FZF\jl6#%Vthe~base~matrix~off~all~matrices~(f
or~algs~An,..,~Gn)GF0F06#F>%8simplefunction_B_matrixGt+Fhil6,F^jlF_jlFUF^[lFct%
#DIGF`jlFajl%#DMG%$LenGF1F0@%Fcjl@%5Ffjl3Fa[m-Fgn6$F]el%1B_matrix_truegenGFeelF
h[mC$@%/F:*&-Fa]qFeflF9-Fa]qF`\mF9Fh[mC&>Fg\lF^v>Fg[lFhfl>F[o7#-FdoFgjm>Fbo7#-F
doFi`l@)3/Fjjl-Fdo6$F:Fg\l/Fjjl-Fdo6$F:Fg[lFh[mF__q-Fap6#*&-Ff]m6$*&&FboFhrF9&F
as6$FjsF[rF9/F[rF^^mF9F`^mF9Fb_q-Fap6#,$*&-Ff]m6$*&&F[oFhrF9&Fas6$Fb^mF[rF9/F[r
F^_mF9Fa_mF9FCC)>F[_l-%0unfold_B_matrixGF^o>8,&-Fdo6$F[jm-F]jm6#%'simpleG6#-%$c
atG6$Fjv%*_unfoldedG>8-,&F__mF9F9F9-F]zFfaq@)/F[_lF:Fh[m-Fgn6$F[_lF\dl>F[_l-F]t
6%f*FfdlF0FdtF0@%Ffn-F^cp6#*&F]ipF9-%:simplefunction_ADE_matrixG6$F^ipFasF9-F\c
qFiwF0F0F0F[_lF_aq-Fgn6$F[_lFin>F[_l-F^cp6#*&-F`bl6#F[_lF9-F\cq6$-F_ipFfcqF_aqF
9>F[_l-F\cq6$F[_lF_aqFaz@%F`bqFh[mC$@'FabqC$@%-Fgn6$-Fdo6$F9F[_lFin@%/-Fdo6$F:-
F_ip6#FddqFjjl-Fap6#-%%subsG6$<#/&Fjjl6#F\bqF:F[_lC'>Fiy-Fdo6$F9Fddq>F[o7#-Fdo6
#-Fdo6$F>Fddq>Fbo7#-Fdo6#-Fdo6$F>-Fdo6$F>F[_l>Fbo,&&F[o6#;,&F__mF9FCF9F__mF9&Fb
o6#;F\gpF_^mF9>F_aq7$&&F[o6#;F9,&F__mF9FGF9F0Fb^m@%/-Fdo6$F:FddqFjjlF\eqC'>FiyF
9>F[o7#-FdoF[eq>Fbo7#-Fdo6#Fefq>FboFhfq>F_aqFagq-Fap6#*&FiyF9&Fb[m6#&&F_aq6#;F9
,&-F]o6#F_aqF9FCF9F0F9F_cq@%/-Fdo6$F:FicqFjjlF\eqC$>FiyFddq>F_aqFahq@%/-Fdo6$F:
F[_lFjjlF\eqC$>FiyF9>F_aq7#-FdoFfcq@%/&F_aq6#F`iqF:Ffhq-Fap6#*&FiyF9&Fb[m6#&7$&
&F_aq6#;F9,&F`iqF9FGF9F0,&&F_aq6#F_iqF9FdjqF9F0F96#%]qthis~is~the~function~for~
a~simple~lie~algebra,~that~does~the~simplification~of~algebras~of~type~BnGF0F06
#F>%0unfold_F_matrixGt+6#'FeapFju6$F^jlF_jlF]qF0C%>F[o7#-Fdo6#F^v>Fbo7#-Fdo6#Fh
fl@%30F[o,$FboFC/-%&F42E6G6#,&F[oF9FboF9Fa`pFh[mC%>F[o-F\]rF`_m>Fbo-F\]rF\s@%5/
F[oFa`p/FboFa`pFh[m-Fap6#-%.generalexpandG6%-Ff]m6$FU/FU-F]t6%f*FfdlF0FdtF0&Fas
6#&F6F0F0F0F0F[oFb[m-Ff]m6$FU/FU-F]t6%f*FfdlF0FdtF0Fc^rF0F0F0FboFb[mFju6#%JDoes
~the~unfolding~of~a~whole~epxression.GF0F06#F9%/epsilon_type_DGt+6%'FeqF,'FfqF,
Fjil6%FUF^[lFWF1F0C%>FZF:?(F[oF9F9F\oF_o?(FboF9F9F\hmF_o@$2FboF[o>FZ,&FZF9-Fhhp
6$*(F]bmF9&FasF\sF9&FfuFj^pF9F>F9-Fap6#-Fhhp6$FZF>6#%!GF0F06#F@F\]rt+F0F0F1F0C$
F^q@%/FbxF:CV>-F\]r6#7&F9F:F:F:7$7(F9F:F:F:F:F:7(F:F:F:F:F9F:>-F\]r6#7&F:F9F:F:
7$7(F:F9F:F:F:F:7(F:F:F:F9F:F:>-F\]r6#7&F:F:F9F:7#7(F:F:F9F:F:F:>-F\]r6#7&F:F:F
:F97#7(F:F:F:F:F:F9>-F\]r6#7&F9F9F:F:7$7(F9F9F:F:F:F:7(F:F:F:F9F9F:>-F\]r6#7&F:
F9F9F:7$7(F:F9F9F:F:F:7(F:F:F9F9F:F:>-F\]r6#7&F:F:F9F97#7(F:F:F9F:F:F9>-F\]r6#7
&F9F9F9F:7$7(F9F9F9F:F:F:7(F:F:F9F9F9F:>-F\]r6#7&F:F9F9F97$7(F:F9F9F:F:F97(F:F:
F9F9F:F9>-F\]r6#7&F9F9F9F97$7(F9F9F9F:F:F97(F:F:F9F9F9F9>-F\]r6#7&F:F>F9F:7#7(F
:F9F9F9F:F:>-F\]r6#7&F:F>F9F97#7(F:F9F9F9F:F9>-F\]r6#7&F9F>F9F:7$7(F9F9F9F9F:F:
7(F:F9F9F9F9F:>-F\]r6#7&F:F>F>F97#7(F:F9F>F9F:F9>-F\]r6#7&F9F>F9F97$7(F9F9F9F9F
:F97(F:F9F9F9F9F9>-F\]r6#7&F>F>F9F:7#7(F9F9F9F9F9F:>-F\]r6#7&F9F>F>F97$7(F9F9F>
F9F:F97(F:F9F>F9F9F9>-F\]r6#7&F>F>F9F97#7(F9F9F9F9F9F9>-F\]r6#7&F9F@F>F97$7(F9F
>F>F9F:F97(F:F9F>F>F9F9>-F\]r6#7&F>F>F>F97#7(F9F9F>F9F9F9>-F\]r6#7&F>F@F>F97$7(
F9F>F>F9F9F97(F9F9F>F>F9F9>-F\]r6#7&F>F[jmF>F97#7(F9F>F>F>F9F9>-F\]r6#7&F>F[jmF
@F97#7(F9F>F@F>F9F9>-F\]r6#7&F>F[jmF@F>7#7(F9F>F@F>F9F>>-F\]r6#,$7&FCF:F:F:F9,$
7$7(FCF:F:F:F:F:7(F:F:F:F:FCF:F9>-F\]r6#,$7&F:FCF:F:F9,$7$7(F:FCF:F:F:F:7(F:F:F
:FCF:F:F9>-F\]r6#,$7&F:F:FCF:F9,$7#7(F:F:FCF:F:F:F9>-F\]r6#,$7&F:F:F:FCF9,$7#7(
F:F:F:F:F:FCF9>-F\]r6#,$7&FCFCF:F:F9,$7$7(FCFCF:F:F:F:7(F:F:F:FCFCF:F9>-F\]r6#,
$7&F:FCFCF:F9,$7$7(F:FCFCF:F:F:7(F:F:FCFCF:F:F9>-F\]r6#,$7&F:F:FCFCF9,$7#7(F:F:
FCF:F:FCF9>-F\]r6#,$7&FCFCFCF:F9,$7$7(FCFCFCF:F:F:7(F:F:FCFCFCF:F9>-F\]r6#,$7&F
:FCFCFCF9,$7$7(F:FCFCF:F:FC7(F:F:FCFCF:FCF9>-F\]r6#,$7&FCFCFCFCF9,$7$7(FCFCFCF:
F:FC7(F:F:FCFCFCFCF9>-F\]r6#,$7&F:FGFCF:F9,$7#7(F:FCFCFCF:F:F9>-F\]r6#,$7&F:FGF
CFCF9,$7#7(F:FCFCFCF:FCF9>-F\]r6#,$7&FCFGFCF:F9,$7$7(FCFCFCFCF:F:7(F:FCFCFCFCF:
F9>-F\]r6#,$7&F:FGFGFCF9,$7#7(F:FCFGFCF:FCF9>-F\]r6#,$7&FCFGFCFCF9,$7$7(FCFCFCF
CF:FC7(F:FCFCFCFCFCF9>-F\]r6#,$7&FGFGFCF:F9,$7#7(FCFCFCFCFCF:F9>-F\]r6#,$7&FCFG
FGFCF9,$7$7(FCFCFGFCF:FC7(F:FCFGFCFCFCF9>-F\]r6#,$7&FGFGFCFCF9,$7#7(FCFCFCFCFCF
CF9>-F\]r6#,$7&FCFIFGFCF9,$7$7(FCFGFGFCF:FC7(F:FCFGFGFCFCF9>-F\]r6#,$7&FGFGFGFC
F9,$7#7(FCFCFGFCFCFCF9>-F\]r6#,$7&FGFIFGFCF9,$7$7(FCFGFGFCFCFC7(FCFCFGFGFCFCF9>
-F\]r6#,$7&FGFi^oFGFCF9,$7#7(FCFGFGFGFCFCF9>-F\]r6#,$7&FGFi^oFIFCF9,$7#7(FCFGFI
FGFCFCF9>-F\]r6#,$7&FGFi^oFIFGF9,$7#7(FCFGFIFGFCFGF9>-F\]r6#7#F97$Figs7#F^im>-F
\]r6#7#F>7$F_hs7#F[jm>-F\]r6#7#F@7#Fehs>-F\]r6#Fahs7#7#""'F_`p6#%fnthis~is~for~
looking~up~what~indices~in~F4~unfold~into~in~E6GF0F06#F:%*resettabsGt+6#'%"lG-F
-6#%%nameGF0F1F0-Fap6#-F]t6$t+F\ilF0F0F0-%'subsopG6$/F[jmF^gl-F]jmF^oF0F0F06#F9
F66#%9Deletes~remember~tables.GF0F06#F9%.mainlsimplifyGt+FP6,%(ismixedGF\q%'New
AlgG%%ListG%"RG%"SGFd[l%)AlgaboveGF[dm%$TMPGF1F0C'>F[ot+6$FRF\q6$F[dmF[[tF1F0C%
>F[o-Fdo6$F[jm-F]jm6#%*directsumG>FboFcbp@'-Fdu6$Fbo&&F[oF]hmF\]l-Fap6#F`\t-Fdu
6$Fbo&Fa\tFjx-Fap6#Ff\t-FapF]hmF0F0F06#F>@'FaxFcxFgx>FboFix>FboFjv@/-Fgn6$Fbo%(
quotalgGC&>F_aq-Fdo6$F[jm-F]jm6#Fa]t>Fg[l&7#&F_aqF\sF\]l>Fg\l-Ffjs6$F6Fg[l@)/Fg
\lF:Fh[m-Fgn6$Fg\lFin-Fap6#-F^cp6#*&-F`blFgjmF9-%-quotsimplifyG6$-F_ipFgjmFboF9
-Fgn6$Fg\lF\dl-Fap6#-F]t6$t+F\ilF0F0F0@%Ffn*&F]ipF9-Fj^t6$F^ipFevF9-Fj^t6$F6Fev
F0F06$F\qFbo6#F9Fg\l-Fap6#-Fj^t6$Fg\lFboFjcl-Fap6#-F]t6$f*F\ilF0FdtF0@%Ffn-F^cp
6#*&F]ipF9-FfjsFg_tF9-FfjsFi_tF0F0Fj_tF6Ffn-Fap6#-F^cp6#*&F]ipF9-Ffjs6$F^ipFboF
9-Fgn6$Fbo%+triangularG-Fap6#-%3triangularsimplifyG6$F6FboFhuC$>Fg\l-Fju6$-Ffjs
6$F^vFbo-Ffjs6$FhflFbo@)F]_t-Fap6#-F]t6$f*F\ilF0FdtF0@%FfnFf`tFj`tF0F0Fj_tFg\lF
a^t-Fap6#-F^cp6#*&Fh^tF9-FfjsF[_tF9F`^tC$>-FfjsFiatF:Fh[mC%>Fiy-Fdo6$F9Fg\l>F[_
l-Fdo6$F>Fg\l@&-Fgn6$FiyFin@%F_cq-Fap6#*(-F`bl6#FiyF9FecqF9-Ffjs6$-Fju6$-F_ipFa
dtFicqFboF9-Fap6#*&F`dtF9-Ffjs6$-Fju6$FfdtF[_lFboF9F_cq-Fap6#*&FecqF9-Ffjs6$-Fj
u6$FiyFicqFboF95-FduFiatFjfl@%55-Fgn6$Fbo%*withrulesG-Fgn6$FboFeaq-Fgn6$Fbo%'af
fineG-Fap6#-%'reduceGFiatFeel-F]p6%%=%1~is~not~a~generator~in~%2.GF6Fbo@$-Fgn6$
FboF[\tC$>FZ-F[oFiat@%/FZFboFh[m>FboFZ@%Fhet-Fap6#-Feft6$-Fju6$FiyF[_lFboC$-F]z
F\s@)-%#&=GFhgtC%Faz>FactF:Fh[m-%#&>GFhgtC&Faz>F\bq,$-Ffjs6$-Fju6$F[_lFiyFboFC>
FactF\bq-FapFdeq53-F`uFhgt-Fdu6$F[_lFbo3-Fgn6$F[_lFju-F\v6$FiyFddqC&Faz>F\bqFgg
t>FactF\bqFjhtC&Faz>F\bq,&-Ffjs6$-Fju6$-FjuFditFefqFboF9-Ffjs6$-Fju6$Fddq-Fju6$
FiyFefqFboF9>FactF\bqFjht6#%a]lmainlsimplify(expression<,algname>)~simplifies~a
n~expression~containing~Hall~Monomials~|+~~~~~~~~~~~~~~and~returns~the~simplifi
ed~expression;~precondition:~in~the~expression~brackets~|+~~~~~~~~~~~~~~have~to
~be~placed~around~constant~*~generator~~(ie~instead~of~2*x&*y~use~|+~~~~~~~~~~~
~~~(2*x)&*y)GF0F06#F9%0unfold_G_matrixGt+F0Fd]nF1F0C$F^q@'FdelC.>F[oFj]n>FboFix
>FZF]^n>-FjjtFcgoFjdo>-FjjtF[doFado>-FjjtF[`oFa`o>-FjjtFg[oFI>-FjjtF]gnF9>-Fjjt
F`anF@>-Fjjt6$-Fav6#-Fju6$FganFganFZF\is>-Fjjt6$-Fav6#-Fju6$FbgnFbgnFZF>>-Fjjt6
$-Fav6#-Fju6$FganFbgnFZFIFd^pC$>Fj^pF[_p@%3F]_p/F`_p7#,$Fe_pFC-Fap6#-FjjtFj_pFh
[mF_`pF\_rF0F06#F:%1unfoldh_B_matrixGt+6$F[\rF^[qF0F]qF0@)3/F`\rFas/Fd\rFas-Fap
6#-F[^r6%,&&-Fdo6$F:F^vF]hmF9&F[_u6#,&FasF9F9F9F9,&&-Fdo6$F:FhflF]hmF9&Fb_uF^_u
F9FjuFc^u-Fap6#-F[^r6%Fi^uFhflFjuFd^u-Fap6#-F[^r6%F^vF`_uFjuFeel6#%XDoes~the~un
folding~of~a~whole~expression~involving~h's.GF0F06#F>%1unfoldh_G_matrixGt+F`^uF
0F1F0@%/-Fjjt6$Fj]nFjvF:-Fap6#-Fjjt6$-Fav6#-Fju6$-Fdo6$F>Fj]n-Fdo6$F9Fj]nFjv-Fa
p6#Fd`uF]`uF0F06#F>%%&!!>Gt+F_alF0F1F0-Fap6#-%.revcomparewtsG6%F6FbamFas6#%iqli
st~&!!>~list~defines~the~operator~"&!!>",~which~is~interface~to~the~|+~~~~~~~~~
~~~~~~~~function~revcomparewtsGF0F06#F>%&AnmatGt+6#F^[qF0FgqF0C$@$2F6F9-F]p6$%9
subscript~%1~is~too~low.GF6-Fap6#-F[[q6$F6F66#%7generates~an~An~matrixGF0F06#F9
%(leadingGt+Figp6$%(MinTermGFd[lF1F0C%>Fbo-FggpF^o@%-Fgn6$FboF\dl@%FgxC%-F]z6#F
ix>F[o&-%%sortG6$Fd_pF`uF\]lFaz>F[oF^du>F[oFbo-FapF`_m6#%esPicks~out~the~leadin
g~term~from~the~sum~(the~term~with~the~maximum~value),|+~~~~~~~~~~~~~~~~and~als
o~checks~for~the~terms~to~be~homogenous.G6#FjvF06#F9%$&!>Gt+F_alF0F1F0-Fap6#-Fi
alF[bu6#%dqlist~&!>~list~defines~the~operator~"&!>",~which~is~interface~to~the~
|+~~~~~~~~~~~~~~~~~function~comparewtsGF0F06#F>%6type/B_matrix_truegenGt+6#'%#b
iGF,F0F1F0-Feal6#3-Fgn6$F6Ffcm0-F\dpF^oFbr6#%ZDefines~the~indices~of~true~gener
ators~for~b[n]~algebras.GF0F06#F9Fj^tt+6$Fjgp'%(FactAlgGFgis6+%&BasisGFUF^[lF[d
m%*StableSetGFd[lF\qFjcm%'weightGF]qF0C+>F[rFd]t>Fg\l&7#&F[rF]hmF\]l>Fg[l&F\guF
jx>F_aq-Fhw6$F6Fg\l>F[o-%*quotbasisG6$F_aqFas@$/F__mF:Fh[m>Fiy&&F[r6$Fas%*stabl
esetGFjx@%-Fcy6$F_aq7#-F^r6$F:/FboF_aq>Fiy-F]t6&t+6%FgdlFhdl%"zGF0F0F0@$-F]al6$
-Fhw6$-F_cuFeuFfuFasF6F0F0F06#F@FiyF_aqFg\l>Fiy-F]t6&t+FihuF0F0F0@$-FcyF]iuF6F0
F0F06#F@FiyF_aqFg\l@%-F46$F6F[oFeel?(FZF9F9-F]oFadtF_oC$>F[_l-%&subwdG6%&FiyFbp
F6Fg\l@$0F[_lFbrC%>F[_l,&F6F9-Ffjs6$-%%compG6$&F[_lF0Fg\lFg\lFC@)F`bqFh[mF_cq-F
ap6#-F^cp6#*&FecqF9-Fj^t6$FicqFasF9Fabq-Fap6#-F]t6$t+F\ilF0F0F0@%Ffn-F^cp6#*&F]
ipF9-Fj^t6$F^ipT$F9-Fj^t6$F6Fb\vF0F06$FcfuFas6#F9F[_l-Fap6#-Fj^t6$F[_lFasFfsF0F
0F06#F>%)repbasisGt+6$'FddmF,'%$RepG%&hwrepG6$F\[t%+dorepbasisGF]qF0C'>Fbot+6%F
ddmF\q%$HWVG6'FUF^[lFc[q%"TGF\[tFgqF0@'5F]y-Fidu6$F67#-F^r6$F:/F[oF6F`y/F6F`^v-
Fap6#7#FfuC&>F[rF6>FiyFbr?(F[oF9F9,&-%$mulG6$,&-F]^lFbpF9F9F9/FZF6F9FCF9F_oC%>F
iy7$&FiyF0&-F]t6(f*6'Fgdl%#wlG%"rGFct%#owGF0FdtF0&-F]t6(t+6'FdwFgdlF]`vFctF^`v6
#%"tGF0F0C$>F[o7#-Ffgl6$F6%#ktG@%30F6Ffu-F`u6$&F[oF\]lFasF^gl-F\]q6$-F\]q6$7$Fa
sFjsF_dlF_flF0F0F06#F^imFasF6FfuFbemFeemF0F0F0F0-%&basisG6$F[rFasFdvFfuFasF6F0?
(FboFgrFCF9F_o@%/F[sF:>F[sF]sFfs@$2F:Fbo>F[sFcs-FapFadt6#%KCalculates~the~basis
~for~a~representation.GF06$Fd]vFbo6#F@-F]z6#&&-Fdo6$F[jm-F]jm6#Fb]v6$FasFeclFjx
>F[o-Fbo6%F6Fibv&F[cvF]hmFazFdduFcbvF0F06#F>%-quotrepbasisGt+6$F_]v'%(QuotRepG%
(quotrepG6&FUF[jlFfq%"PGF1F0C&>Fbo&-Fdo6$F[jm-F]jm6#%*submoduleG6%&&-Fdo6$F[jm-
F]jm6#FjcvF]hmFjxF6F^hp@$4-Fgn6$Fbo%)listlistGC$-%/submodulebasisG6$F6Ffdv>FboF
_dv>FZ-Fiav6$F6&FgdvF\]l@%/FboFbrF`pC%>F[r-F]t6$t+6#Fdis6#Fc[qF0F0@$30F6Fbr-F46
%F9F6.F[oF[oF0F0F06#F9Fbo?(F[oFgrFCF9F_o>FZ-F^js6$/&F[rF`_mF^glFZF`p6#%TCalcula
tes~the~basis~for~a~quotient~representation.GF0F06#F>%6type/C_matrix_truegenGt+
6#'%#ciGF,F0F1F0-Feal6#3Fieu0-FhzF^oFbr6#%ZDefines~the~indices~of~true~generato
rs~for~c[n]~algebras.GF0F06#F9%0unfold_C_matrixGt+Fj[r6'F^jlF_jl%#AIG%#LBGFUF]q
F0C(>F[oF_\r>FboFc\r@%/F[oFi\r>F[r7$F[oFbo>F[r7%F[oFboF^]r>FZFbr?(FiyF9F9FgrF_o
C$>&F[rFadt-Fhz6#Fbiv@&/FbivFbrFh[m2FiyF@@%/&FbivF\]l&FbivFjx>FZ7$&FZF0&Fb[m6#&
FjivF0>FZ7$F^jv,&F_jvF9&Fb[m6#&F[jvF0F9-Fap6#-F[^r6%&FZF\]l&FZFjxFjuF\_rF0F06#F
9%/type/generatorGt+6#%$loeGF0F1F0-FduFg_m6#%<Defines~the~generator~type.GF0F06
#F9%,functionizeGt+6$'%%exprGFS'F\qFgis6(%&tableGFU%$lhsG%$rhsG%%tempG%(entries
GFgqF0C%@%5Fcjl/-Fdo6$F[jm-F]jm6#F\ftF^glF_`pC%>FZF^v>F[rFhfl>F[_l&Fg\wF]hm?(Fb
oF9F9-F]oFfcqF_oC$>Fiy-Fdo6$F9&F[_lF\s@$5553/FZ-Fdo6$F9Fiy/F[r-Fdo6$F>Fiy333333
333-Fgn6$FZF`hl-Fgn6$F[rF`hl-Fgn6$F]^wF`hl-Fgn6$F`^wF`hl-Fhem6$7#-Fdo6#F]^wFgis
-Fhem6$7#-Fdo6#F`^wFgis/F]]m-Fdo6$F:F]^w/-F]o6#Fe\m-F]o6#Fe_w/F`]m-Fdo6$F:F`^w/
-F]o6#Fh\m-F]o6#Fj_w33333F[_wF__wFc_wF]`wF``wF_^w33333F\^wF]_wFa_wFh_wFe`wFh`w-
Fap6#-Fdo6$F>Ff]wF_`p6#%\]lfunctionize(expression),~if~possible,~finds~the~rule
~in~the~lookup~table~that~|+~~~~~~~~~~~~~~~suits~the~given~expression,~and~retu
rns~that~rule~converted~into~a~maple~function;|+~~~~~~~~~~~~~~~when~no~correspo
nding~rule~is~found~or~the~lookup~table~is~empty~FAIL~is~|+~~~~~~~~~~~~~~~retur
nedGF0F06#F>F_ipt+FP6&FUFV%)nonconstG%%FlagGF0F0C&>FZF9>F[rF>@%Ffn?(F[oF9F9F\oF
_oC$>FboFco@$4FgoC$>FZFbo>F[r,&F[rF9FCF9C$-F]p6#%Fargument~of~PickTerm~is~not~a
~productG@$1F[rF:-F]p6#%Nmore~than~one~non-constant~factor~in~PickTermGF`pF0F0F
06#F9%&GnmatGt+Fabu6#F[jlFgqF0C&@$0F6F>-F]p6$%Ealgebra~of~type~%1~is~not~suppor
ted.G&FRF^o>F[oFjbu>&F[o6$,&F6F9FCF9F6FI-Fap6#-F]jmF`_m6#%7generates~an~Gn~matr
ixGF0F06#F9%&BnmatGt+FabuF[dwFgqF0C&@$2F6F>Febu>F[oFjbu>&F[o6$F6FgdwFGFhdw6#%7g
enerates~an~Bn~matrixGF0F06#F9%4mainquotrepsimplifyGt+6$FRFa]v6%FW%,ReduceTerms
G%&HWRepGF]qF0C&>Fbot+6&FRFddm%$HWRG%#SMG6(F[jlFfqFU%"CGF[^vFc[qF0F0C%>F[o&F`dv
6%FbemFasF^hp@$4-Fgn6$F[oF`evC$-Fcev6$FasFbem>F[oFjfw@'/F6F:Fh[m/F[oFbrFeelC'>F
bo-F\]v6$FasFfu>F[r-%&arrayG6#7#-F^r6$F:/FZF^^m@)FjclC$>Fiy-F]t6$f*Fd`vF0FdtF0@
%FfnF^ipF6F0F0F0F]el?(FZF9F9F_^mF_o@%-F46%&FboFbpFiy.F[_l@%-Fgn6$-Fdo6$F[_lF6Fi
n>&F[rFbpF]ip>FfiwF9>FfiwF:3Ffn-F46%FhflFboF_iw>&F[rFfcqF]ip-F46%F6FboF_iw>F]jw
F9-F]p6%%7%1~is~not~in~basis~%2.GF6Fbo>F[r,&-F\]q6$-&%.LinearAlgebraG6#%5Vector
MatrixMultiplyG6$-&%'VectorG6#%$rowG6#-F]t6%t+6$Fdis%#clGFbfvF0F0@$FffvFbhmF0F0
F06#F>F[oF[r-F\jlF`_mF-F9-F\]q6$F[rF-FC-Fap6#-Ff]m6$*&FfiwF9F^iwF9/FZ;F9FgrF0F0
F06#F[jm>FZFiev@'Fjcl>F[o-F]t6%f*6$Fe`vF]`vF0FdtF0@%Ffn-F^cp6#*&F]ipF9-%0mainre
psimplifyGF]cqF9-Fb]xFiwF0F0F0F6FZFfn>F[o-F^cp6#*&F]ipF9-Fb]x6$F^ipFZF9>F[o-Fb]
x6$F6FZ-Fap6#-Fbo6&F[o-Fhw6$-F]jm6#-F_eq6$/&F[cvFbpF9F[o&&F[cvF_jmFjxFZFfdv6#%j
nThis~is~a~simplification~function~for~quotient~representations.GF0F06#F>%8simp
lefunction_C_matrixGt+Fhil6+F^jlF_jlFUF^[lFctFchvF`jlFajl%#AMGF1F0C$F^q@%Fcjl@%
5Ffjl3Fa[m-Fgn6$F]el%1C_matrix_truegenGFeelFh[mC$@%/F:*&-F^_xFeflF9-F^_xF`\mF9F
h[mC&>Fg\lF^v>Fg[lFhfl>F[oFh^q>FboF[_q@)F^_qFh[mF__qFe_qFb_qF_`qC(>F[_l-F`hvF^o
>F_aqF`aqF^bq@)F`bqFh[mFabq>F[_l-F]t6%f*FfdlF0FdtF0@%FfnFhbqF^cqF0F0F0F[_lF_aqF
_cq>F[_lFbcq>F[_lF[dqFaz@%F`bqFh[mC%@%Fabq>F_aqFddq>F_aqF[_l@%-Fgn6$F_aqFinC$>F
iy-F`blFaiq>F_aq-F_ipFaiq>FiyF9@%/-Fdo6$F:F_aqFjjl-Fap6#-F_eq6$<#-F^r6$/&FjjlFb
pF:/FZ;F]bq,&F__mF>FCF9F[_lC'>F[o7#-FdoFaiq>Fbo7#-F^r6$F:F`gt?(F[rF9F9F\gpF_o>F
[`q,&Ff`qF9&F[o6#,(F__mF9F9F9F[rFCF9>F[`qFf`q-Fap6#*&FiyF9&FbbxFa^mF96#%]qthis~
is~the~function~for~a~simple~lie~algebra,~that~does~the~simplification~of~algeb
ras~of~type~CnGFgduF06#F>%%&!!<Gt+F_alF0F1F0-Fap6#-FjauFjal6#%iqlist~&!!<~list~
defines~the~operator~"&!!<",~which~is~interface~to~the~|+~~~~~~~~~~~~~~~~~funct
ion~revcomparewtsGF0F06#F>%1unfoldh_F_matrixGt+F`^uF0F]qF0-Fap6#-F[^r6%-Ff]m6$F
U/FU-F]t6%f*FfdlF0FdtF0Fc^rF0F0F0-F\]r6#F_\rF[_u-Ff]m6$FU/FU-F]t6%f*FfdlF0FdtF0
Fc^rF0F0F0-F\]r6#Fc\rFb_uFjuF]`uF0F06#F>%+NewAlgTypeGt+6#'%#ATGFa`mF0F]qF0>(_F0
%&type/GF6f*6#%$algGF0FdtF0-Feal6#30-Fdo6$F[jm-F]jm6#Fb\vF^gl-F46$7#F67#-%(indi
cesG6#FegxF0F06$FifxF66#%JGeneric~function~to~define~algebra~types.GF0F06#F9%+l
ieconvertGt+6#'F[[tF-6$%-dolieconvertGFWF]qF0C%>F[ot+6$F[[tF\q6&%&LeastGFU%&Pre
viG%$MonGFgqF0@'/F\oF:F`yF]hl@%-Fgn6$Fe^rFgis-FapFd^rFeelC)>F[o&F6F\]l?(FboF9F9
F\oF_o@$-F`u6$-%*listtolieGF^^l-F`jxF`_m>F[oF]s@$-F]ht6$-F`jx6#&F66#F\oFajxF`y>
FboF9>F[rFbr?(F0F9F9F01FboF\oC&>FZFbo?(F0F9F9F0-F]htF^jx>Fbo,&FboF9F9F9@%F`gt>F
[r7$&F[rF0F]s>F[r7%Fg[y&&F66#;FZ,&FboF9FGF9F0&F66#;,&FboF9FCF9Fbo>FboFc[y-Fap6#
-FevFjav6#%ZBrackets~a~list~of~names~properly~according~to~Lie~rules.GFgdu6$Fih
xF[o6#F>@'FaxFcxFgxC%F[du>Fbo-F[o6$F6FixFaz>Fbo-F[oFg_mFdz6#%:Wrapper~to~do_lie
convert.GF0F06#F9%$&!<Gt+F_alF0F1F0-Fap6#Fhal6#%dqlist~&!<~list~defines~the~ope
rator~"&!<",~which~is~interface~to~the~|+~~~~~~~~~~~~~~~~~function~comparewtsGF
0F06#F>%/type/reordexprGt+6#FeapF0F1F0-Feal6#55/Fhjl%$&<<G/Fhjl%$&==G/Fhjl%$&>>
G6#%_oDefines~expressions~with~the~reorder~operator~types~&<<,&>>~and~&==.GF0F0
6#F9Fegut+Ffp6.FUF^[lF[dm%(EntriesGFjcmF\qFffuFefu%)DeleteItG%)maximizeGFd[lFcf
uF]qF0C+>F\bqt+6$FeqFfq6$FUFWF1F0C$@%/F\oF\hmC$>FboFbr?(F[oF9F9F\oF_o@%2FbhmF]b
m>Fbo7$Fb^mF]bm>Fbo7$Fb^mFbhm-F]p6%%Kweights~%1~and~%2~are~of~different~length.
GF6FasFdzF0F0F06#F>@)FaxFcxF]yF`yFgx>8/Fix>Fh`yFjv@%-Fgn6$Fh`yFa]tC&>FZFd]t>F[r
7#-F^hxFbp>F[_l&&FZ6#Fh`yF\]l>Fiy&FdayFjx-F]p6$%Cquotient~algebra~%1~isn't~defi
ned.GFh`y@%-F46%7$Fh`yF]huF[r.Fc[q@%53-F]al6$F6&7#&FZ6#&&F[rFbfvF0F\]l-FcyF_^v3
-FcyFdby-F]alF_^v>Fg\l&FfbyFjx@'34-FiduFdbyF[cyC%>8.-F\bq6$FebyF6>Fg\l-F]hu6%7#
&FiimFadtFgcyF[_l>-Fa]t6$Fh`yF]hu6$FgcyFg\l34-Fe]yFdbyF^cyC%>Fgcy,$-F\bq6$,$Feb
yFC,$F6FCFC>Fg\lF[dy>F`dyFbdyC$>Fg\l-F]hu6%F]dyF6F[_l>F`dyFbguC$>Fg\lFaey>F`dyF
bgu>Fg[l-Fdp6$F6F[_l@%F[cy>Fg\l-F]t6$f*F\ilF0FdtF0@$-F]al6$-Fhw6$-F_cuFi_tFevT&
F6F0F06&F\qF[_lFhpF6Fg\l>Fg\l-F]t6$f*F\ilF0FdtF0@$-FcyFafyF6F0F0FffyFg\l>F[oF9?
(F0F9F9F032F:-F]oFi`l1F[oFagyC&>F_aqF%>FboF9?(F0F9F9F01Fbo-F]oFgjmC$@$0-Faju6%&
Fg\lF\s&Fg[lF`_mF[_lFbrC$>F_aqF_oFfs>FboFc[y@%F_aq>Fg[l-F^js6$/F[oF^glFg[l>F[o,
&F[oF9F9F9Fh`l6#%MCalculates~the~basis~of~a~quotient~algebras.GF0F06#F9F\[vt+6%
'FctFeis'%)unsimplVGFS'Fe]nFeis6-%"UGF\qFUF`ix%,BracketListGF_ix%(LowMarkG%)Hig
hMarkG%"VG%(leadofVG%(VinlistGF1F0C4@'2F[jmFbxFcx/FbxF[jm>Fbo&Ffx6#F[jm>FboFjvF
jgt>F_aq-%*lsimplifyG6$FasFbo>F\bq-F_cu6$F_aqFbo@(-Fgn6$F_aqF\dl@$/-FhwFijyFbr-
F]p6$%@terms~in~%1~are~not~homogenous.GF_aq/F_aqF:Fh[m-Fho6$F_aqFjo-F]p6#%inmid
dle~term~in~simplifies~to~a~constant,~which~is~not~allowed.G@$-Fgn6$F\bqFinC$>F
_aq-F^cp6#*&-F`blFdeqFCF_aqF9>F\bq-F^cp6#*&Fa\zFCF\bqF9>Fgcy-F]t6$t+F\ilF0F0F0@
%FfnF^ipF6F0F0F06#F97#-F^cl6$F\bqFbo>F[o7%F^el-Fdo6#Fgcy-FdoFh`m>Fg\l,&F\oF9F9F
9>Fg[l,&F\oF9-F]oFb]zF9>F[_l&-F`du6$F[oF`uF\]l>FiyFbr>FZF9?(F0F9F9F01FZF__mC&>F
[rFZ?(F0F9F9F03-F]ht6$FecpF[_l2FZF__m>FZ,&FZF9F9F9@)31F[rFg\l2Fg[lFZ>Fiy7$Ff_v7
$&&F[o6#;F[r,&Fg\lF9FCF9F07$7#F_aq-Fdhx6$&F[o6#;,&Fg[lF9F9F9FZFbo3F\_z1Fg\lFZC$
@%/F[rFg\l>Fiy7$Ff_vFg_z>Fiy7$Ff_v7$Fa_zFg_z>FZFg[l/F[rFZ>Fiy7$Ff_vFecp@%3Fb`z/
FZFg[l>FiyFd`z>Fiy7$Ff_v&F[o6#;F[rFZ>FZFi^z?(FZF9F9F]juF_o@%-Fgn6$FcjuF->Fcju-F
dhx6$FcjuFbo>Fcju-Fdhx6$7#FcjuFbo>Fiy-Fdhx6$FiyFboFaz@%/FiyFbr-F]p6#%Rbad~words
,~cannot~be~converted~to~a~Hall~MonomialG-Fap6#-F`jx6$FiyF:6#%LComputes~the~com
position~of~the~expression.GF0F06#F@Fb]xt+F\fw6%FW%%UAlgG%+ApplyRulesGF]qF0C(>F
Zt+6&%%TermG%)RuleFuncGFa]vF\q6)F\[tF^[lFd[l%(TempNegG%)TempZeroG%$NZEGFUF1F0C&
@%-Fgn6$FasF-C$>F[oFas>F[_lF:C$>F[oFbr>F[_lF9>FZ7#-FfglF^o?(FboF9F9-F]oFbpF_o@&
-Fidu6$-Fhw6$&FZF\sFbem7#-F^r6$F:/Fg\lF`ezFh[m3/F[_lF9-%$&!=GF_ez>F[o7$Fjs/Fbez
-Fas6#Fbez-Fap6#-F\]q6%-F\]q6%-F_eq6$F[o7#-F^cl6$F6FbemF_dlFbemF_flFbem6#%WRemo
ve~terms~with~positive~weight~elements,~keep~rest.GF0F06#F[jm>F[o-F]jm6#-F_eq6$
/FccvF9F6>Fbo&FjbvF\]l@'-Fgn6$F[oF\dl>F[o-F]t6%f*6$Fe`v%#uaGF0FdtF0@%Ffn-F^cp6#
*&F]ipF9-%*asimplifyGF]cqF9-FdhzFiwF0F0F0F[oFbo-Fgn6$F[oFin>F[o-F^cp6#*&-F`blF`
_mF9-Fdhz6$-F_ipF`_mFboF9>F[o-FdhzFj^p@)Fggz>F[o-F]t6't+6&FgdlFhdlFjhuFdwF0F0F0
@%Ffn*&F]ipF9-Fev6&F^ipFasFfuFbemF9-Fev6&F6FasFfuFbemF0F06$FcczFZ6#F[jmF[o&F[cv
6$Fas%(replaceGFasFboFfhz>F[o*&F\izF9-FZ6&F_izF`jzFasFboF9-Fgn6$F[oFjo@%/F[oF9-
Fap6#Fccv-Fap6#*&F[oF9FccvF9>F[o-FZ6&F[oF`jzFasFbo-Fap6#-F_dl6%F[oFccvFas6#%WTh
is~is~a~simplification~function~for~representations.GF0F06#F>%-type/mixedwtGt+F
djpF0F1F0-Feal6#3-Fhem6$F6F^gm-Fhem6$F6Fjem6#%?Defines~the~mixed~weight~type.GF
0F06#F9%*regmatrixGt+6''%&labelGFgis'%&gens1GFgis'%&gens2GFgis'Fe`vFgisF^[qF[dw
F1F0C%@0/FbemFeqC$>F[o-F_bu6#Feem>-Feaq6$F6Fgn6$%+ADE_matrixG%'type_AG/Fbem%"DG
C$>F[o-%&DnmatGFf][l>Fh][l6$F[^[l%'type_DG/FbemFbclC$>F[o-%&EnmatGFf][l>Fh][l6$
F[^[l%'type_EG/FbemFfqC$>F[o-F^ewFf][l>Fh][l6$%)B_matrixGFe^[l/FbemFgfwC$>F[o-%
&CnmatGFf][l>Fh][l6$%)C_matrixGF\^[l/Fbem%"FGC%-F\]rF0>F[o-%&FnmatGFf][l>Fh][l6
$%)F_matrixGF]_[l/FbemFRC&-Ff_m6%FasFfuF6-FjjtFj`[l>F[o-FicwFf][l>Fh][l6$%)G_ma
trixG%'type_GG>-FeaqF^oFjdwFddu6#%`ogenerates~and~registers~with~simple()~a~mat
rix~of~given~type~and~sizeGF0F06#F^im%/epsilon_type_AGt+Fa_r6&FUF^[lFWF_[qF1F0C
&>FZF:>F[r-F]o6#-F\]q6$-&%'linalgGFa[x6$FfuF9F-?(F[oF9F9F\oF_o?(FboF9F9F\hmF_o@
$53/F[oFc[y1,$FboF>F[r3/F[oFb\y2F[r,$F[oF>>FZF\`rFb`r6#%@epsilon~function~for~A
n~algebraGF0F06#F@%/epsilon_type_EGt+Fa_rFia[lF1F0C&>FZF:>F[rF]b[l?(F[oF9F9F\oF
_o?(FboF9F9F\hmF_o@$5553Fjb[l1F[o,&F[rF9FIF93/F[oFbd[l/Fbo,&F[rF9FGF93/F[oFfd[l
/FboF^cw3Fdd[l/FboF[r>FZF\`rFb`r6#%@epsilon~function~for~En~algebraGF0F06#F@Fje
zt+F_alF0F1F0-Fap6#-Feal6#F\bl6#%dqlist~&!=~list~defines~the~operator~"&!=",~wh
ich~is~interface~to~the~|+~~~~~~~~~~~~~~~~~function~comparewtsGF0F06#F>Feftt+Fi
[w6)F_\wF`\w%&conslG%&consrG%%consGF[dm%%funcGFgqF0C$@)FjflFeel3Fhu/F^vFhflFh[m
-Fgn6$FasF\ftC$>Fg\l-Fg[wFiw@$0Fg\lFa`p-Fap6#-Fg\l6$F`\rFd\rC)>F[_lFaaq-%*unpro
tectG6$-Fav6#%,MATRIX_TYPEG-Fav6#%.MATRIX_LACINGG-F]zF]hm@%-Fgn6$FasFaftC$>6$Fg
g[lFdg[l&F[_l6$-Fhaq6$Fas%(_simpleGFgn>Fg\l-%5affinesimplefunctionG6$F6&F[_l6#F
ah[lC$>F^h[l&F[_l6$FasFgn>Fg\l-(%0simplefunction_GFgg[l6$F6&F[_lF]hmFaz-%(prote
ctGFag[l@$Fhf[l-FapFgjmFeel6#%awreduce(expression)~simplifies~an~expression~acc
ording~to~the~rules~defined~in~the~|+~~~~~~~~~~~~~~~lookup~table;~reduce()~can~
only~simplify~an~expression~involving~two~terms,~not~|+~~~~~~~~~~~~~~~moreG6$Fd
g[lFgg[lF06#F>%1mixedtrisimplifyGt+6'Fiil'F\dvFgis'F][tFgis'%"NGFgisF\\w6*FUFWF
d[lF`jlFajl%%LgenG%%Alg1G%%Alg2GF1F0C(@%5-Fdu6$F6FeemF^hlFeelC$>F[rF^v>FiyFhfl>
F[_l7#-F^cl6$F[rFeem@)-FduFj\v>Fg\lFas-Fdu6$F[_lFfu>Fg\lFfu-Fdu6$F[_lFbem>Fg\lF
bemC$>FZ-F\j[l6'F[rFasFfuFbemFeem@)/FZF:Fh[m-Fgn6$FZFin-Fap6#-F^cp6#*&-F`blFbpF
9-F\j[l6'-Fju6$-F_ipFbpFiyFasFfuFbemFeemF9-Fgn6$FZF\dl-Fap6#-F]t6$t+F\ilF0F0F0@
%Ffn-F^cp6#*&F]ipF9-F\j[l6'-FjuFg_tFefyT(T*T,F9-F\j[l6'-FjuFi_tFefyF]^\lF^^\lF_
^\lF0F06,FajlFiyF\dvFasF][tFfuFbj[lFbemF\qFeem6#F9FZ-Fap6#-F\j[l6'-Fju6$FZFiyFa
sFfuFbemFeem>F[_l7#-F^cl6$FiyFeem@)Fd[\l>Fg[lFasFf[\l>Fg[lFfuFi[\l>Fg[lFbemC$>F
Z-F\j[l6'FiyFasFfuFbemFeem@)Fa\\lFh[mFb\\l-Fap6#-F^cp6#*&Fi\\lF9-F\j[l6'-Fju6$F
[rF^]\lFasFfuFbemFeemF9F_]\l-Fap6#-F]t6$t+F\ilF0F0F0@%Ffn-F^cp6#*&F]ipF9-F\j[l6
'-Fju6$FevF^ipFefyF]^\lF^^\lF_^\lF9-F\j[l6'-Fju6$FevF6FefyF]^\lF^^\lF_^\lF0F06,
F`jlF[rF\dvFasF][tFfuFbj[lFbemF\qFeem6#F9FZ-Fap6#-F\j[l6'-Fju6$F[rFZFasFfuFbemF
eem@)/Fg\lFg[lFeel353-Fdu6$F`[\lFas-Fdu6$F\_\lFbem3-Fdu6$F`[\lFbem-Fdu6$F\_\lFa
s45-Fcy6$,&-FhwFb[\lF9-FhwF^_\lF97#-F^r6$F:/F[oF]c\l-F]alF[c\lFh[m-Fdu6$F[rFg\l
@%-Fdu6$FiyFg[l-Fap6#-FeftF[[\l-Fap6#,&-F\j[l6'-Fju6$-Fju6$F[rF]^wF`^wFasFfuFbe
mFeemF9-F\j[l6'-Fju6$F]^w-Fju6$F[rF`^wFasFfuFbemFeemF9-Fap6#,&-F\j[l6'-Fju6$-Fd
o6$F9F[r-Fju6$-Fdo6$F>F[rFiyFasFfuFbemFeemF9-F\j[l6'-Fju6$-Fju6$Fbe\lFiyFfe\lFa
sFfuFbemFeemF9Ff`rF0F06#F^imFi_[lt+FabuF[dwFgqF0C&@$FbewFebu>F[oFjbu>FedwFGFhdw
6#%7generates~an~Cn~matrixGF0F06#F9F\ftt+F0F0F1F0F^q6#%_oWithrules()~is~used~as
~a~lookuptable~for~rules~defined~for~algebras.GF0F06#F:Fb^[lt+FabuF[dwFgqF0C(@$
2F6F@Febu>F[o-F[[qFfew>&F[o6$,&F6F9FGF9F6FC>&F[o6$F6Fdg\lFC>&F[oF[cuF>Fhdw6#%7g
enerates~an~Dn~matrixGF0F06#F9Fhatt+6$FiilF\\w6(F_[tF\dvF][tFbj[l%$simGFUFgqF0C
&>Fiyt+6&Fgdl%)Algname1G%)Algname2G%)Algname3G6$F\[l%(AlgnameGF1F0C%>F[o7#-F^cl
Fd\v@(-Fdu6$F[oFas>FboFas-Fdu6$F[oFfu>FboFfu-Fdu6$F[oFbem>FboFbem@%FfnF[at-Fap6
#FactF0F06$F\qFas6#F[jm>6%F[rFZFbo-F^r6$F[_l/F[_l7#&-Fdo6$F[jm-F]jm6#FdatF]hm>F
[o-F\j[l6'F6FboFZF[rFas@'/F[oF:Fh[mFggz-Fap6#-F]t6'FiyF[oFboFZF[r-Fap6#-Fiy6&F[
oFboFZF[rFf`rF0F06#F>F\cqt+FhilF]jlF1F0@%Fcjl@%5Ffjl3Fa[m-Fgn6$F]el%3ADE_matrix
_truegenGFeelFh[mC$@%/F:*&-F\cqFeflF9-F\cqF`\mF9Fh[mC&>FZF^v>F[rFhfl>F[oFe\m>Fb
oFh\m@-F[]mFh[mF\]mFb]mF_]mFc^m/-%%scpdG6%F[oFboFasFG-Fap6#*&)FC-(%)epsilon_GFd
g[lF]]]lF9-Ff]m6$*&Fj^mF9&FjjlFj]mF9F]_mF9/F[]]lFC-Fap6#*&Fa]]lF9&-F]t6%f*FfdlF
0FdtF0Fc^rF0F0F07#F^]rFb[mF0F9Fh[m6#%]qthis~is~the~function~for~a~simple~lie~al
gebra,~that~does~the~simplification~of~algebras~An,~Dn,~EnGF0F06#F>%.mainasimpl
ifyGt+FP6/Fd[l%%ConsGFUF^[lF\q%$PreG%%PostG%%ElemGFWFhcz%(NewTermGFf]q%'EvdAlgG
F]qF0C&@'FaxFcxFgx>FiyFix>FiyFjv@%-Fgn6$Fiy%'unienvG>80&-Fdo6$F[jm-F]jm6#Fe_]lF
adt-F]p6$%J%1~is~not~a~universal~enveloping~algebra.GFiy@)F\hl@%5Fjfl-Fdu6$F6Fi
y>F_aqF6-F]p6%FhftF6FiyFjcl>F_aq-F]t6%t+FfdlF0F0F0@%Ffn-F^cp6#*&F]ipF9-Fe^]lF]c
qF9-Fe^]lFiwF0F0F06#F>F6FiyFfn>F_aq-F^cp6#*&F]ipF9-Fe^]l6$F^ipFiyF9C'>Fg[l7#-F^
cl6%F6Fiy%*KeepTermsG-F]zFadt?(FZF9F9,&FagyF9FCF9F_o@$-Faht6$&Fg[lFbp&Fg[l6#Fi^
zFfsFaz@%/FZFagy>F_aqF6C*>F[oFeb]l>Feb]lFfb]l>Ffb]lF[o@%2F9FZ>F[_l-F\]q6$&Fg[l6
#;F9,&FZF9FCF9F_dl>F[_lF9@%2Fi^zFagy>Fg\l-F\]q6$&Fg[l6#;,&FZF9F>F9FagyF_dl>Fg\l
F9>F_aq,&-F_dl6$-F_dl6$F[_l-Fejy6$-Fju6$Ffb]lFeb]lFg_]lFg\lF9-F\]q6$Fg[lF_dlF9>
FZF9?(F0F9F9F0F_oC&@'3F[[z1FZF`iq>F\bq-Fdo6$FZF_aq34F[[z1FZF9>F\bqF_aqFfs@%Fj[z
C$>FboFa\z>F\bq-F_ipFdeq>FboF9>Fgcy-Fe^]l6$F\bqFiy@%3/FgcyF\bq0FgcyF:>FZFi^z@%F
[[z>F_aq-F]jm6#-F^js6$/FZ*&FboF9FgcyF9F_aq>F_aqFag]l-Fap6#-F^cpFaiq6#%fnThis~is
~a~simplification~function~for~associative~algebras.GF0F06#F9%*NewOpTypeGt+6#F_
`mF0F]qF0>F[gxf*F^^yF0FdtF0-Feal6#/FhjlFb\vF0F06$F``mF66#%KGeneric~function~to~
define~operator~types.GF0F06#F9%8simplefunction_F_matrixGt+Fhil6+F^jlF_jlFUFctF
e]n%#EIGF`jlFajl%#EMGF1F0@%Fcjl@%5Ffjl3Fa[m-Fgn6$F]el%1F_matrix_truegenGFeelFh[
mC$@%/F:*&-Feh]lFeflF9-Feh]lF`\mF9Fh[mC&>Fg\lF^v>Fg[lFhfl>F[oFh^q>FboF[_q@)F^_q
Fh[mF__qFb]mFb_qFc^mC(>F[_l-Fh[rF^o>F_aqF`aqF^bq@)F`bqFh[mFabq>F[_l-F]t6%f*Ffdl
F0FdtF0@%FfnFhbqF^cqF0F0F0F[_lF_aqF_cq>F[_lFbcq>F[_lF[dqFaz@%F`bqFh[mC%@%Fabq>F
_aqFddq>F_aqF[_l@%FhaxC$>F[rF\bx>F_aqF^bx>F[rF9@%Fabx-Fap6#-F_eq6$<%/&FjjlFajyF
:/&Fjjl6#F^imF:/&Fjjl6#F\isFj[^lF[_lC%>F[oFbcx>Fbo7&,&FaavF9&F[oF]\^lF9,&&F[oFj
xF9&F[oFajyF9&F[oF^^n&F[oF`\^l-Fap6#*&F[rF9FbdxF96#%]qthis~is~the~function~for~
a~simple~lie~algebra,~that~does~the~simplification~of~algebras~of~type~F4GF0F06
#F>Fcyt+F_alF0F1F0-Fap6#-Feal6#5F]euF\bl6#%fqlist~&!>=~list~defines~the~operato
r~"&!>=",~which~is~interface~to~the~|+~~~~~~~~~~~~~~~~~function~comparewtsGF0F0
6#F>%%grabGt+6#F\\wF0F1F0@%-Fgn6$F6Fecl-Fap6#7#&FcjmF^oF_`p6#%Qreturns~the~gene
rators~for~the~requested~algebraGF0F06#F9Fajut+6$'%#E1GFS'%#E2GFS6'FUFWFeqFfqF
\qF1F0C'@'2F@FbxFcxFdel>FiyF]^n>FiyFjv>FZ7#-F^cl6$-F_cuFd`]lFiy>F[r7#-F^cl6$-F_
cu6$FasFiyFiy@%Fe\l>Fbo7%FbrF6FbrC$>FboFbr?(F[oF9F9,(FgrF9F\ezFCF9F9F_o@$/FZ&F[
r6#;F[o,(F[oF9F\ezF9FCF9C$>Fbo7%&F[r6#;F9,&F[oF9FCF9F6&F[r6#;,&F[oF9F\ezF9FgrFf
sFdz6#%`qsubwd()~picks~out~the~subword~E1~in~E2~and~returns~a~and~b~in~a~list,|
+~~~~~~~~~~~~~~~~where~E2~=~aE1bGF0F06#F>%%dumpGt+F0F0F1F0@%32F:Fbx-Fgn6$Fj]n%*
procedureG@%0-Fdo6$F[jm-F]jmFg^pF^gl-Fap6#Fdb^lF\glF_`p6#%indebugging~tool,~dum
ps~a~procedures~hash~table~(remember~table)GF0F06#F:Fcevt+6$F_]v'%'SubModGFddv6
(FfqF[jlFa]vF\q%1dosubmodulebasisGFUF]qF0C->Fiyt+6&FddmF\qFi]v%+SubModGensGFj]v
FgqF0@'5F]^v4-F46$F%-F]t6'f*6&Fcw%$hwvGFdwFctF0FdtF0-Feal6#-Fe]y6$-Fhw6$-F]jm6#
-F_eq6$/FasF9F6FbemFfuF0F0F0FbemFfuF6FasF`yFd^vFe^vC$>F[r-F]t6'f*F_d^lF0FdtF0@$
/Fed^lFfuF6F0F0F0FbemFfuF6Fas@%0F[rFbr-FapFhrC&>F[rF6>FiyFbr?(F[oF9F9F\_vF_oC%>
Fiy7$Ff_v&-F]t6(f*F[`vF0FdtF0&-F]t6(f*Fc`vF0FdtF0-F_dlFauF0F0F0FasF6FfuFbemFeem
F0F0F0F0Fhav-Fev6&FgvFasFfuFbemFfuFasF6F0?(FboFgrFCF9F_o@%F]bv>F[sF]sFfs@$F`bv>
F[sFcsFbbv6#%FCalculates~the~basis~for~a~submodule.GF06$Fac^lFiy6#F[jm>FZ&F`dvF
_cv>F[rFi^x>F[o-FiavF\^xF\z>Fbo-%'matrixG6#-F]t6't+6&FeapF]`v%#blG%$bllG6$%"sGF
c[qF0F0C$>F[o-%,repsimplifyGFiw@+Fggz-Fap6#-F]t6&t+6%Fe`vF^h^lF_h^lFbfvF0F0@'3F
fn-F46%-Fdo6$FCF6FasFhfv-Fap6#7%-F^r6$F:/FevFaa^lF]ip-F^r6$F:/Fev;FihyFfu-F46%F
6FasFhfv-Fap6#7%Ffi^lF9Fii^l-F]p6%FcjwF6FasF0F06$FUFev6#F@F[oFfuFbem3Ffhz-F46%-
Fdo6$FCF[oFfu.Fbo-Fap6#7%-F^r6$F:/Fev;F9Fb\yF\iz-F^r6$F:/Fev;Fc[yFbem-F46%F[oFf
uF[[_l-Fap6#7%F_[_lF9Fc[_lF\[]l-Fap6#7#-F^r6$F:/Fev;F9Fbem-F]p6%FcjwF[oFfuF0F06
$FUF[_l6#F[jm-Fiy6&F6F[rFh^x7#&F`dvF]hmFZF[oF__mFaz@%/F^hpF:>Fbo-F\]q6$-&Fcb[l6
#%*gaussjordGF\sF`ev>Fbo-F\]q6$-Fhhp6$-%*GaussjordGF\sF^hpF`ev>Fbo-F]t6$f*FafvF
0FdtF0@$0F67#-F^r6$F:/FevF6F6F0F0Fe\_lFbo>-Fddv6%FasF6F^hpFbo-Fap6#-F]t6%f*6$Fd
isF^h^lF0FdtF0@$Fefv-Ff]m6$*&&F66#FevF9&FasFc__lF9/FevFedpF0F0Fe\_lFboF[oFcbvF0
F06#F>Fj^[lt+FabuF[dwFgqF0C(@$4-F46$F6<%F\is""(Fb`o-F]p6$Fadw&FbclF^o>F[oF`g\l>
&F[o6$,&F6F9FIF9F6FC>&F[o6$F6Ff`_lFC>Fig\lF>Fhdw6#%7generates~an~En~matrixGF0F0
6#F9%1unfoldh_C_matrixGt+F`^uFbfvF]qF0C$>F[o,&FasF>FCF9@)30,(F[oF9F9F9F`\rFCF`
\r0,(F[oF9F9F9Fd\rFCFd\r-Fap6#-F[^r6%,&F^vF9&F[_u6#Ffa_lF9,&FhflF9&Fb_u6#Fha_lF
9FjuFea_l-Fap6#-F[^r6%F]b_lFhflFjuFga_l-Fap6#-F[^r6%F^vF`b_lFjuFeelF]`uF0F06#F>
F[^rt+6%'%#ElGFccl'%#ErGFcclF_`m6&%'TermsXG%'TermsYGF\q%+CheckConstGF1F0C$@%Fa_
^lC$>FZF`jy>F[rF_o>F[rF%@)3Fjcl-Fgn6$FasF\dl@%F[r-Fap6#-F]t6't+FgizF0F0F0-F]t6'
t+FgizF0F0F0-Ffu6%FasF6FbemF0F0F06#F[jmFasF6FfuFbemF0F0F06#F[jmF6FasFfuFZ-Fap6#
-F]t6&t+FihuF0F0F0-F]t6&t+FihuF0F0F0-FfuFauF0F0F06#F@FasF6FfuF0F0F06#F@F6FasFfu
Fjcl@%F[r-Fap6#-F]t6't+FgizF0F0F0-Ffu6%F6FasFbemF0F0F06#F[jmF6FasFfuFZ-Fap6#-F]
t6&t+FihuF0F0F0-FfuFiwF0F0F06#F@F6FasFfuF^d_l@%F[r-Fap6#-F]t6't+FgizF0F0F0Fid_l
F0F0F06#F[jmFasF6FfuFZ-Fap6#-F]t6&t+FihuF0F0F0Fee_lF0F0F06#F@FasF6Ffu@%F[r-Fap6
#-Ffu6%-F^cpF^o-F^cpF]hmFZ-Fap6#-Ffu6$Fjg_lF[h_l6#%^oExpands~a~Lie/associative~
expression,~pulls~constants~to~the~front.GF0F06#F@Feclt+F0F0F1F0F^q6#%YAlgebra(
)~is~used~to~store~algebras~in~its~lookup~table.GF0F06#F:Fjaut+F\`mFfclF1F0C%@&
Ff`mFi`mF\amFdam?(F[oF\oFCF9F_o@(FiamFabmFcbmFabmFjbmF]cmFabm6#%fochecks~for~W1
~to~be~less~than~or~equal~to~W2~in~REVERSE~lexicographic~orderGF0F06#F@Fjhmt+Ff
hx6-FUF^[lFc[q%*SimplListG%%VarsG%%GensGF\q%(VectorsG%.LinIndVectorsGFW%+addele
mentGF1F0C.>Fgcyt+6$%(ElementGFdqF0F1F0@'Ffn-Fap6#-Fafm6$Fas<#F^ip4Fjfl-Fap6#-F
afm6$Fas<#F6Fi\tF0F0F06#F>@$FaxFcx@%Fgx>Fg\lFix>Fg\lFjv>FiyFgdm>F[r-F]hw6#Fedp?
(F[oF9F9F\oF_oC$>F_gv-Fejy6$F]bmFg\l@%-Fgn6$F_gvF\dl?(FboF9F9-F]o6#F_gvF_o>Fiy-
Fgcy6$-Fdo6$FboF_gvFiy>Fiy-Fgcy6$F_gvFiy>Fg[l7#-F^r6$-&Fcb[l6#%'vectorG6$F]juF:
/F[o;F9-F]o6#7#-F^hxFhr?(F[oF9F9F_]`lF_o?(FboF9F9F]juF_o@(Fg[`l?(FZF9F9Fj[`lF_o
@&-Fgn6$-Fdo6$FZF_gvFin@$/-F_ip6#Fj]`l&FiyF\s>&F_hyF\s,&Fb^`lF9-Fdo6$F9Fj]`lF9/
Fj]`lF`^`l>Fb^`l,&Fb^`lF9F9F93-Fgn6$F_gvFin/-Fdo6$F>F_gvF`^`l>Fb^`l,&Fb^`lF9-F`
blF[\`lF9/F_gvF`^`l>Fb^`lFh^`l>F_aq-&Fcb[l6#FiavFi`l>F\bqFbr?(F[oF9F9F`iqF_o@$-
F46%&F_aqF`_mFg[l.FZ>F\bq7$-FdoFdeq&F6FbpFjht6#%jqindependent([list~of~expressi
ons])~picks~out~the~linearly~independent~expressions~|+~~~~~~~~~~~~~~~from~the~
listGF0F06#F9F]hut+6$'F\[t-F-6#FS'%&AlphaGFfcm6XF\qFUF^[lFc[qF][t%"QGF\dvFd[l%&
time0G%&time1G%&time2G%&time3G%&time4G%&time5G%&time6G%&time7G%(timetotG%)timeh
allG%(timelocG%(timeredG%(timesubG%)timecompG%+printcountG%+leadofTempG%%BetaG%
&WordsG%%NextGFjpFhcz%%LeadG%)TempLeadG%&PLeadG%$PwtG%$SwtG%#iiG%#jjG%&icancG%#
nQG%#nPG%&shiftG%%QdblG%&newelG%"HG%$monG%&coef1G%&coef2G%#i1G%#i2G%%flagG%'cou
ntQG%(rescaleG%'insertG%*remidleadG%,double_listGFgqF0C3>8Vt+6#F[hp6$Fd[lFbb`lF
1F0C%>F[oFecu@%F\[]lFh[m>Fbo-F_cu6$F[oFjv@%-Fgn6$FboFin-Fap6#*&F[oF9-F`blF\sFCF
dduF0F0F06#F9>8Wt+6$FbclF\[l6$%%HalfGF\[tF1F0C%>F[o-%&truncG6#,$F\hmFh_l@+/FasF
br>FboF[hx/F\hmF9@%-F`u6$F6&FasF\]l>Fbo7$F6F[el>Fbo7$F[elF6-F`u6$F6Fbhm>Fbo7$&-
Fev6$F6&FasF`a^lF0&&Fas6#;F[oF\hmF0-F]htFhf`l>Fbo7%&F^g`lF0F6F_g`l>Fbo7$&&Fas6#
;F9F[oF0&-Fev6$F6&Fas6#;FihyF\hmF0FdzF0F06$Fhc`lF`e`l6#F>>8Xt+6#F\[l6&FUF^a`lFd
[lFab`lF1F0C&>FboF6>F[oF9?(F0F9F9F02F[oF_^mC%>F[rF9@$-F]ht6$F\ep&Fbo6#FihyC%>F[
rF:>FZ,&Fdi`lF9F\epFC@%0FZF:C$>FZ-FevFbp>Fbo7$&&FboF[h`lF0&-T%6$FZ&Fbo6#;,&F[oF
9F>F9F_^mF0>Fbo-F^js6$FghyFbo>F[o,&F[oF9F[rF9FdzF0F06&Fgc`lF]d`lFhc`lF`e`l6#F9>
8Yt+6#%$SumG6&F\[lF[^vF][tFUF1F0C(>F[oFbr>FboFbr>FZFbr@&Fjcl>FZF]el0F6F:>FZF[hx
?(F[rF9F9F\ezF_o@%-Fgn6$&FZFhrFinC$>Fbo7$Fb^m-F`bl6#Fd\al>F[o7$Fjs-F_ipFi\alC$>
Fbo7$Fb^mF9>F[o7$FjsFd\al-Fap6#F[iv6#%fvConverts~a~sum~into~a~pair~of~lists~-~f
irst~list~is~a~list~of~monomials,~the~~~~~~~~second~is~the~list~of~coefficients
.|+~~~~~~~~~~~~~Returns:~[[list~of~monomials],~[list~of~coefficients]]GF0F06#F9
@'Fa_^lFcxFdel>F[oF]^n>F[oFjv-F]zF`_m>8<7#-F^r6$F:/FboFas@%-Fcy6$FasF\^al>8?F_o
>Fe^alF%>FiyFbr>8EFbr?(FboF9F9F\oF_oC'>Fg[l-Fejy6$F]sF[o>8;-F_cu6$Fg[lF[o@$-Fgn
6$Fg[lF\dl@$/-FhwFb_alFbr-F]p6$Fb[zFg[l>Fg[l-F]d`lFi`l@$0Fg[lF:C$>F`_alFa_al@%F
e^al@$-F]al6$-Fhw6$F`_alF[oFasC$>Fiy7$Ff_vFg[l>Fi^al7$&Fi^alF0Fe`al@$-FcyFd`alC
$>FiyFi`al>Fi^alF[aal>Fg\lFbr>8CFbr>8DFbr?(F0F9F9F00F\^alFasC-?(FboF9F9-F]o6#F
\^alF_o@%/&F\^alF\sF``r>F_balF:C$@%Fe^al>F_bal,&F_balF9F9F9>F_bal,&F_balF9FCF9F
fs>F[_lFbr>FboF9>8UF:?(F0F9F9F01FboF]ju@%/&Fi^alF\sF\^alC%>F[_l7$F^[vF`^`l>Fiy-
F^js6$/FboF^glFiy>Fi^al-F^js6$FfcalFi^al>FboFc[y>8LFbr?(FboF9F9Fa]wF_o>F\dal7$-
Fdo6#F\dal-Fc[al6#Ff]w>8N-F`du6$-Fdp6$F\^alF[oF`u>8JFhgy?(F0F9F9F032F:Fa]w2F:-F
]o6#FedalC'>8O&FedalF\]l>Fedal-F^js6$/F9F^glFedal>Fg[lFbr?(FboF9F9Fa]wF_o@$-F46
%Fdeal&F\dal6$FboF9.8G>Fg[l7$F\_q7$Fbo&F\dal6%FboF>Fbfal@$F`gyC)>8R&Fg[lF[_n>8P
&Fg[l6$F9F>@$2F9Fagy?(FboFagyFCF>F_oC&>8S&Fg[lF`fal>8Q&Fg[l6$FboF>>8M-Fggp6#,&&
F[_l6#FfgalF9*(FigalF9F^galFC&F[_l6#F[galF9FC@%/F]halF:C$>F[_l-F^js6$/FfgalF^gl
F[_l>F\dal-F^js6$F\ialF\dalC$>F[_l-F^js6$/FfgalF]halF[_l>F\dal-F^js6$/Ffgal-Fc[
al6#F]halF\dal>8TF9>FZF9?(F0F9F9F031FZF[eal/F\jalF9C$@$53Fe^al-F]al6$&FfaalFbpF
\^al34Fe^al-FcyFgjalC$>Fg[l-Faju6%&Fg\lFbpFdealF[o@$0Fg[lFbrC%>F\jalF:>Fdhal-Fg
gp6#,&FdhalF9-F^cp6#*&F^galF9-Fejy6$-F\[v6$&Fg[lF0F[oF[oF9FC@%/FdhalF:C$>F[_l-F
^js6$/F[galF^glF[_l>F\dal-F^js6$Fg\blF\dal>F\dal-F^js6$/F[gal-Fc[al6#FdhalF\dal
>FZFi^z@$FajalC(>Fg\l7$Fi^q*&FdhalF9F^galFC>Fdaal7$-Fdo6#FdaalFdeal>Ffaal7$-Fdo
6#FfaalF\^al>F[_lFe\bl>F\dalFi\bl>Fjbal,&FjbalF9F9F9?(FboF9F9FhgyF_o?(FZ,(FhgyF
9FjbalFCF9F9F9FhgyF_o@&-F`u6$&FdaalF\s&FdaalFbpC$>8=-%(overlapG6%Fi^blFj^blF[o@
$0F]_blFbr?(F[rF9F9-F]o6#F]_blF_o@$53Fe^al-F]al6$-Ff]m6$-Fhw6$FdisF[o/Fdis7%&&&
F]_blFhrF\]lF0&&Fc`blFjxF0&&Fc`blF^^nF0Fas3Fjjal-FcyFj_blC$>Fg[l,&-Fejy6$-F\[v6
&FbrF^hyFg`blF[oF[oF9-Fejy6$-F\[v6&Fb`blF`[blFbrF[oF[oFC@$F^`alC%>Fg[lF\`al>Fiy
Fi`al>Fi^al7$F\aal-Fhw6#Fa_al-FahtFh^blC$>F]_bl-F__bl6%Fj^blFi^blF[o@$Fb_bl?(F[
rF9F9Fd_blF_o@$Fg_blC$>Fg[l,&-Fejy6$-F\[v6&FbrF`[blFg`blF[oF[oF9-Fejy6$-F\[v6&F
b`blF^hyFbrF[oF[oFC@$F^`alC%>Fg[lF\`al>FiyFi`al>Fi^alFjablFazFgi[l6#%:Calculate
s~the~stableset.GF0F06#F>%8type/ADE_matrix_truegenGt+6#'%%adeiGF,F0F1F0-Feal6#3
Fieu/-F\]]l6%F6F6&FaaqFgduF>6#%fnDefines~the~indices~of~true~generators~for~ade
[n]~algebras.GF0F06#F9F`jxt+6#F[[t6%FUFWF^b]lFgqF0C&@'FaxFcxFgx>FZF_o>FZF%@&4-F
gn6$F6F-@%/FZF_o-Fap6#-F`jx6$F[hxF:-Fap6#-F`jx6#F[hxFcixFh[m@%33/FZF%F]hl5-Fgn6
$Fe^rF\dl-Fgn6$Fe^r%)functionG>Fbo-F_cu6$Fe^rFjvC$@%-Fgn6$FjixF-@%Fcebl>Fbo-F`j
x6$FjixF:>Fbo-F`jx6#Fjix>FboFjix?(F[oF>F9F\oF_o@%-Fgn6$F]bmF-@%Fcebl>Fbo-Fju6$F
bo-F`jx6$F]bmF:>Fbo-Fju6$Fbo-F`jxFdep>Fbo-Fju6$FboF]bmFdz6#%PConverts~a~list~to
~a~lieexpression~(with~&*-s).GF0F06#F9%.normalrankingGt+Fg`p6)F\[l%&valueGFbj[l
%"fG%,gensinorderGFU%)positionGF]qF0C(>F[oFcbp>FboF:>FZ,&-F]o6#FjwF9F9F9>F[r*$F
ZFC?(F[_lF9F9F__mF_oC%-F46%&F[oFfcqFjw.Fg\l>Fbo,&FboF9*&Fg\lF9F[rF9F9>F[r*&F[rF
9FZFCFdzFhcpF0F06#F>F]aqt+Fj[r6'F^jlF_jlFd]qFdhvFUF]qF0C(>F[oF_\r>FboFc\r@%Fihv
>F[rF[iv>F[rF]iv>FZFbr?(FiyF9F9FgrF_oC$>Fbiv-F\dpFdiv@&FfivFh[mFgiv@%/F[jvFbr>F
ZF]jv>FZFcjvFhjv6#%JDoes~the~unfolding~of~a~whole~expression.GF0F06#F9F\]]lt+Fa
_r6%FUF^[l%$ResGF1F0C%>FZF:?(F[oF9F9F\oF_o?(FboF9F9F\hmF_o>FZ,&FZF9F_`rF9F`p6#%
^oproduces~the~scalar~product~of~two~lists,~given~the~matrix~for~themGF0F06#F@F
fh[lt+6$FjgpFjil6)%%nlhsG%%nrhsGF_\wF`\wF]f[l%%klhsG%%krhsGF1F0C$@%FcjlC&-F]z6#
-Fhaq6$FjvFch[l@%/F:-F`i[l6$&Fhjl6#&&F]el6#;F9,&F\oF9FCF9F0Fas>FiyF:>FiyF6FazFb
bvC%>FZF^v>F[rFhfl@%5/FZ&FjwF^^n/F[rFg^cl>FiyF:C)>F[o&F]]m6#-Fdo6$;F9,&F\ezF9FC
F9FZ>Fbo&F`]m6#-Fdo6$;F9,&FgrF9FCF9F[r>F[_l-Fdo6$F\ezFZ>Fg\l-Fdo6$FgrF[r>Fiy-Fe
ft6$-FjuFj^p&-Fdo6$F[jm-F]jm6#FaftFgdu@(-Fgn6$FiyF\dl>Fiy-F]t6&f*FihuF0FdtF0@%F
fn-F^cp6#*&F]ipF9&-Fdo6$F:Fai^l6$-Fdo6#F^ip,&FasF9FfuF9F9&Fhjl6$F^elFiaclF0F0F0
FiyF[_lFg\lFjct>Fiy-F^cp6#*&F`dtF9&-Fdo6$F:-Fdo6$FCFiy6$-Fdo6#Ffdt,&F[_lF9Fg\lF
9F90FiyF:>Fiy&-Fdo6$F:Fiy6$-FdoFadtFhbcl>Fiy,&FiyF9**-%&deltaG6$F[_l,$Fg\lFCF9F
[_lF9-%+dotproductG6%F[oFboFc`clF9Fg^clF9F9Fbbv6#%hrthis~is~the~function~for~an
~affine~simple~lie~algebra,~that~does~the~simplification~of~an~expression~invol
ving~only~two~termsGF0F06#F>%.type/htruegenGt+6#'%#hiGF,F0F1F0-Feal6#32F:Fe^r1F
e^r-&Fjjw6#%-RowDimensionG6#Fcdbl6#%`oDefines~the~indices~of~true~generators~fo
r~h's~in~any~simple~algebra.GF0F06#F9%%&!<>Gt+F_alF0F1F0-Fap6#-Feal6#0F6Fas6#%g
qList~&!<>~list~defines~the~operator~"&!<>",~which~is~interface~to~the~|+~~~~~~
~~~~~~~~~~~function~comparewts.GF0F06#F>%6type/F_matrix_truegenGt+6#'%$f4iGF,F0
F1F0-Feal6#0-F\]rF^oFa`p6#%ZDefines~the~indices~of~true~generators~for~f[4]~alg
ebras.GF0F06#F9Fc`[lt+FabuF[dwFgqF0C&@$0F6F[jm-F]p6$Fadw&F^`[lF^o>F[oFjbu>&F[o6
$Fdg\lFgdwFGFhdw6#%7generates~an~Fn~matrixGF0F06#F9F__blt+Fi^^l6*FUFeqFfqFW%$Re
mGF\q%#L1G%#L2GF1F0C*@'Fa_^lFcxFdel>F[_lF]^n>F[_lFjv>Fg\l7#-F^cl6$-F_cuFieyF[_l
>Fg[l7#-F^cl6$-F_cu6$FasF[_lF[_l@%2FagyFhgyC$>Fbo&Fg\l6#;,(FhgyF9FagyFCF9F9Fhgy
>Fiy&Fg\l6#;F9,&FhgyF9FagyFCC$>FboFg\l>FiyFbr>FZFg[l>F[rFbr?(F[oF9F9F_^mF_o@$/&
Fbo6#;F[oF_^m&FZ6#;F9,(F_^mF9F9F9F[oFC>F[r7$Fg[y7%7$Ff_v&&FboF`a^lF0F\jcl&FZ6#;
,(F_^mF9F>F9F[oFCF\ezFee^l6#%droverlap()~picks~out~the~overlaps~of~the~end~of~A
~(1st~arguments)~and~the~|+~~~~~~~~~~~~~~~beginning~of~B~(second~argument)GF0F0
6#F>F0
